### ISSUE TITLE
OCR in Access Object policy

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#1]
Re: https://github.com/crkn-rcdr/Access-Platform/wiki/Access-Object-policy
Continuing discussion started at crkn-rcdr/CIHM-Swift/issues/2

Our current OCR processing takes a single image as input, and generates both a PDF and an XML file as output.  In the past we generated multi-page PDFs, and stored the XML inside the METS record, but the process was generally the same.

Should I assume that a canvas MUST have a reference to an image server image, but MAY also have a reference to a PDF and/or XML file?  Is the intention that the same identifier will be used for all 3 files (image, PDF, XML)?

**Comment by SaschaAdler** [comment]
Your assumption is correct in my understanding, provided that if we were to re-run OCR on an image, we have no intent to hang onto the old output, and can reuse the canvas' noid for the pdf/xml's identifier.

**Comment by RussellMcOrmond** [comment]
Thanks.

Question for @nataliemacdonald 

OCR data within the repository is currently sourced in 2 formats.

* ALTO XML https://www.loc.gov/standards/alto/
* TXTMap  http://canadiana.ca/schema/2012/xsd/txtmap/txtmap.xsd  (which was crosswalked from the custom files that PrimeOCR generated.  That code is no longer active in the platform).

One possibility is to crosswalk the txtmap to ALTO, and drop support for TXTMAP.  While we are loading OCR data into the new Access metadata storage might be a good time to do that.  I remember looking at this possibility when we first adopted ALTO, and thought TXTMAP was a subset and thus conversion would be lossless.

**Comment by nataliemacdonald** [comment]
I'm always a fan of streamlining processes where possible. I don't see the need to be using two methods for sourcing OCR data. ALTO XML has worked well where it has been implemented? I'm asking because I just read that it can have difficulty with high resolution images. I don't know a ton about ALTO, so I will join the listserv.

**Comment by RussellMcOrmond** [comment]
I believe #5 contains all the remaining work on this, so closing.
