### ISSUE TITLE
Import interface (Smelter)

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#100]
Staff will use an admin tool interface for selecting packages to import into the access platform as manifests. Staff can look up package records in `dipstaging` (through accessor logic that needs to be built) by providing a list of slugs (or also by date?). Packages with slugs that are not already in use can be imported.

Related `dipstaging` work is in #99.

**Comment by SaschaAdler** [comment]
There is a functioning tool for this called "Archival Manifest" in sapindale. I think I now finally understand what the name "Archival Manifest" actually means, finally: it's from the archive, as opposed to created inside the access platform. Right?

I like "Import from Preservation" better but whatever works for staff works for me.

**Comment by RussellMcOrmond** [comment]
My recommendation is to use the term "AIP ID" or similar and not "Slug" when referencing records in `dipstaging`.

Those IDs look sorta like slugs at the moment because of the current tie between Preservation and Access platforms, but in the future the AIP ID's will be very different.

See:  https://www.archivematica.org/en/docs/archivematica-1.12/user-manual/archival-storage/aip-structure/

> For example, looking at the AIP name my-aip-d31cc44f-ce01-4e67-affe-513868d9cf3d, my-aip is the name assigned by the user and d31cc44f-ce01-4e67-affe-513868d9cf3d is the UUID generated during ingest.

**Comment by RussellMcOrmond** [comment]
> There is a functioning tool for this called "Archival Manifest" in sapindale. I think I now finally understand what the name "Archival Manifest" actually means, finally: it's from the archive, as opposed to created inside the access platform. Right?

It is a term that William came up with during a much earlier meeting.

Thoughts for other developers:

Those concerning themselves with user experience should think about what the best terminology will be for staff using these tools. Same with the term "Ingest" and "Import", to ensure the distinctions are clear.  It all makes sense to me, but what I think isn't generally the best indicator of what other staff will be thinking :-)   Sounds like good things to add to the Glossary.md

A reminder when porting Sapindale tools to Access-Platform:  Sapindale was written assuming that the web client would be directly talking to CouchDB using https://github.com/crkn-rcdr/upholstery .  CouchDB and other databases and object storage is now being abstracted by Accessor, so no need to think in the older mindset.

To make the connection, the back-end tool which processes the updated `dipstaging` records  is called **Smelter**.

**Comment by SaschaAdler** [comment]
First, we need to show interfaces for querying dipstaging records. There are two methods in AccessHandler for looking things up in dipstaging: `listFromKeys` and `listFromDates`. `listFromKeys` accepts a list of strings; use the same sort of PrefixSelector that adding members uses. `listFromKeys` accepts two strings in the form `yyyy-mm-dd`. (when setting up lapin to use these, you will also need to pass in `ctx.couch.access`, since it looks up whether the slugs are taken)

Second, use the `ImportStatus` objects that these lookups return to build an interface for importing AIPs into manifests. AIPs can be imported if a) their status is neither "not-found" or "processing" b) their slug isn't already taken by a noid.

If an import's slug is taken by a noid, provide a link to that noid's editor, so that the slug can be unassigned there if the user wants. The import's slug should be editable, using a SlugResolver component; if the slug has been edited to one that isn't taken, the import can proceed.

There should probably be a checkbox for every possible import, with a "select all/select none" button.

When the user clicks on a big "import" (or whatever) button, the interface should send the following to lapin:

```ts
{
  user: User;
  import: {
    id: Slug;
    slug: Slug;
  }[]
}
```

where `user` is the User performing the import, and `import` is an array of objects where `id` is the dipstaging id, and `slug` is whatever the slug for the manifest will end up being. They'll usually be identical.

lapin should probably check that all of the slugs are available, by using `resolveSlugs` on the full list and checking the results. It then should call a dipstaging handler method that calls the `requestSmelt` update function with the data

```ts
{
  user: User;
  slug: Slug;
}
```

for each `id` in `import`.

**Comment by RussellMcOrmond** [comment]
I ran `loadseries`, and added notes to the end of[ Some Temporary Processes](https://crkn.sharepoint.com/:w:/s/HeritageTech/EdXsiqIYIslEpoE2-4J2N3ABCnsT49fOEBzS9Av2dMvvHQ?e=lXh8Gs).

This is a set of AIP ID's which need to be smelted.  We should do a walk-through of the current tool https://admin.canadiana.ca/archivalmanifest as hopefully inspiration for the new.


* Packaging date  -- very useful to be able to browse through to get a list of IDs that were recently added, or if you want to go back in time.
* Processing queue - Knowing how many are in the queue, and when the one you are waiting for might be processed, is quite helpful.
* Processing Status -- critical for viewing failures, and in various groupings (as the failure list could be long or tiny).  The success list isn't used as often, but might as well offer the option.  This shouldn't be read-only, and should allow the ability to re-run any failures without having to cut-and-paste ID's.
* "a list I supply" -- the normal text box to put in IDs.  This is the most critical possibility, but shouldn't be the only one as the other views.

The "display details" allows processing to be done, while "display list" is for cutting-and-pasting the IDs into some other tool.

---

```
russell@russell-XPS-13-7390:~$ grep <a AIPID= | sed -e 's/^.*AIPID=//' | sort -u
oocihm.8_01388_1
oocihm.8_01388_2
oocihm.8_01388_3
oocihm.8_01391_1
oocihm.8_01391_3
oocihm.8_01391_4
oocihm.8_01394_2
oocihm.8_01394_3
oocihm.8_01394_4
oocihm.8_01394_5
oocihm.8_01396_1
oocihm.8_01397_2
oocihm.8_01398_1
oocihm.8_01398_2
oocihm.8_01398_4
oocihm.8_01398_6
oocihm.8_01398_7
oocihm.8_01405_1
oocihm.8_01405_2
oocihm.8_01405_3
oocihm.8_01405_4
oocihm.8_01405_5
oocihm.8_01405_6
oocihm.lac_reel_t10864
oocihm.lac_reel_t10866
oocihm.lac_reel_t1931
oocihm.lac_reel_t7180
oocihm.N_00358_19240308
oocihm.N_00358_19240310
oocihm.N_00358_19240311
oocihm.N_00358_19240312
oocihm.N_00358_19240313
oocihm.N_00358_19240314
oocihm.N_00358_19240315
oocihm.N_00358_19240317
oocihm.N_00358_19240318
oocihm.N_00358_19240319
oocihm.N_00358_19240320
russell@russell-XPS-13-7390:~$ 

```

**Comment by DivyaKrishnan26** [comment]
@Sascha here are the questions I have to set Up lapin routes for dipstaging,

1) Should the route to show the records be based on the ListFromKeys or ListfromDates AccessHandler functions? And when creating the route should we create two different routes for each? (Creating a route from ListOfKeys is where I am at currently)

2) If using the ListofDates function,, should it accept a start and end date along with the list? Or we supply just the start and end date? 

3) For the big Import, It is something like the "a list I supply" ?(from sapindale) ? 

4) Last,  should we also be creating individual routes for the different views:
 { byManifestDate, lib, neverSmelted(@RussellMcOrmond  and I had a chat last week on what this view is about), newDip, smeltQueue(Is this similar to Packaging queue) and smeltStatus(Packaging Status) }
 That is something I would want to discuss more on how part. We have different viwes in Sapindale for this I believe.
 
5)Another thing for to know- what is the sync datbase? Is it for the views that is currently there?

**Comment by SaschaAdler** [comment]
>     1. Should the route to show the records be based on the ListFromKeys or ListfromDates AccessHandler functions? And when creating the route should we create two different routes for each? (Creating a route from ListOfKeys is where I am at currently)

One route for each, yeah.

>     2. If using the ListofDates function,, should it accept a start and end date along with the list? Or we supply just the start and end date?

We don't need to provide a list for `listFromDates`, because it gets generated by looking up a view that understands dates. The date strings look like `yyyy-mm-dd` (see the test file).

>     3. For the big Import, It is something like the "a list I supply" ?(from sapindale) ?

That's `listFromKeys`.

>     4. Last,  should we also be creating individual routes for the different views:
>        { byManifestDate, lib, neverSmelted(@RussellMcOrmond  and I had a chat last week on what this view is about), newDip, smeltQueue(Is this similar to Packaging queue) and smeltStatus(Packaging Status) }
>        That is something I would want to discuss more on how part. We have different views in Sapindale for this I believe. Should we want to follow how we have in Sapindale basically?

Sapindale has a few other lookups that I'm not sure we need. Let's start with these two and add others when necessary.

> 5)Another thing for to know- what is the sync database? Is it for the views that is currently there?

The `sync` design document is something Russell put together for other `dipstaging` database work. If we need to add more views we should use the `access` design document.

**Comment by RussellMcOrmond** [comment]
Re:`sync` -- see #278 , as future work we want to do to consolidate/etc.   Please use the new views in design/access for new tools, and we will clean up the deprecated stuff later.
