### ISSUE TITLE
Accessor instantiation

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#103]
Right now the Accessor constructor accepts arguments for CouchDB access. Accessor is also going to need config to point to or use:

- the noid minter
- Swift
- Cantaloupe (maybe? If this is just for the admin tools they can build IIIF image URLs on their own)

Not all uses of accessor will require each service. How do we want to organize this? Do we want to register services without using the accessor constructor? Is CouchDB special in that regard? Can or should we hard-code any of this configuration?

A lot of work we'd like to start on is riding on this, I think.

**Comment by RussellMcOrmond** [comment]
I will remain a fan of environment variables over config files, allowing the Docker configuration to be easier.

Defaults fine to hard-code, but we need to have flexibility for when this is in production to deal with unforseen circumstances. We don't want to have to build a new Docker image because the CouchDB disk got filled or something.

Regularly the couchdb interface will be http://couchdb:5984 from within the application container, but not always.

**Comment by SaschaAdler** [comment]
Right. I think we'll need to add arguments for at least Swift and the noid minter to each instantiation of Accessor, to start.

**Comment by RussellMcOrmond** [comment]
I'm going to see how TypeScript will help, but having the instantiated Accessor object know its capabilities based on how much configuration it is given would be great.

Of course, these are programming errors (asking for a IIIF image server URL for a canvas before initialising the "{scheme}://{server}{/prefix}/"), and we will find these out in testing as well.


I like the idea of being able to say something like:

`thisurl = mycanvas.ImageServerURL({region "square" , size: "150,", rotation: "180",quality: "gray", format: "png"});`

and have the Accessor canvas object know what to do, without the specific application needing to pass in configuration information.

**Comment by SaschaAdler** [comment]
At some point the specific application needs to pass in configuration information, since Accessor is just a library that can be dropped into any environment. What this issue is really driving at is when does that happen?

```js
// accessor instantiation?
const accessor = new Accessor(objectWithEveryPossibleEndpoint)
// whenever, per instance?
accessor.setImageService(imageEndpointUrl)
// not on the instance directly, but whenever you need to use the service?
const manifest = await accessor.get(noid)
if (manifest.isCanvasManifest()) {
  return manifest.imageUrls(imageEndpointUrl, { size: "150," })
} else {
  throw new Error("not what I was expecting");
}
```

I'm leaning toward the `objectWithEveryPossibleButSomeAreOptional` argument to the constructor.
