### ISSUE TITLE
`label` interface

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#106]
`Text` fields have values that are objects that map either [BCP 47 language tags](https://en.wikipedia.org/wiki/IETF_language_tag) or `none` to text strings. These fields are found in the following places:

- any access object's `label` field
- an optional `label` field corresponding to each member of a collection, stored in the collection's member list. Since this is a new feature we might not have to integrate it into the collection member list editor just yet
- the `label` field in each CanvasManifest's canvases list
- more to come, probably (`summary`, for example)

We've already achieved this in sapindale, but it should be ported over. The sapindale component might be a bit bulky for use in the lists described above.

**Comment by RussellMcOrmond** [comment]
Related to #599
