### ISSUE TITLE
"Deleting" an object by unassigning its slug

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#108]
Objects that do not have a slug assigned to them are effectively undiscoverable. While removing an object's slug might not be the most useful thing to do as staff workflows change to work with the new functionality we're creating, it's a requirement for the short-term.

I've generally thought this functionality should be exposed in the admin tools as a "Delete" button, even though nothing will actually be deleted, although I'm open to suggestions. #76 suggests a "bulk delete" interface might also be useful.

From the accessor side of things, we will need to decide on a policy for "deleted" objects that are members of still-perfectly-viable collections. Removing the objects from these collections' member lists seems like the right way to go.

**Comment by RussellMcOrmond** [comment]
I would have thought Objects would be discoverable by Slug or Noid, even if it was not public (Solr discoverability).

Did we want walks to detect manifests which are not in any collection, or collections that are not branches of a "root" collection?  Now that we have collection trees, I feel like we need a root.

**Comment by SaschaAdler** [comment]
A root collection is probably a good idea.

Are you talking about Solr discoverability for source access objects? Otherwise, at least until we implement manifest freezing someday, I'm not sure what utility a slugless object has, and I'm also not sure who will know what noid to use to access the slugless object.

**Comment by RussellMcOrmond** [comment]
I'm not comfortable with automatic deletion of data.  It feels like something other than an automated process should be determining the utility of a slugless object.

My preference remains to have a "virtual collection" of slugless objects that staff can then go through and deliberately trash, or fix the slug for if it was an error..  I want data disappearing to be a deliberate staff action, but one which we have provided tools to make efficient.

**Comment by SaschaAdler** [comment]
I don't disagree with this, and that's why "delete" is in scare-quotes, but we could call it "unassign" instead if you prefer, and put together a list of slugless objects when we get around to it. It'll be interesting to see what's there, especially when we want to build in manifest freezing.
