### ISSUE TITLE
The 'tx' field (Internalmeta, cosearch)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#11]
Currently the 'tx' field is filled in by Hammer by removing all XML tags (and thus positional information) from the OCR XML.  This is stored within hammer.json (array indexes above 0), and then stored in cosearch documents in a 'tx' field.

In 'cosearch' the ID's are slug based, so even canvas documents will need to be generated per-manifest.  This suggests that this field should be generated based on something 'manifest' related, not 'canvas'.

Press manages the cosearch documents, and instead of only getting the "_rev" from the previous document it can also grab previously stored data including a previously stored 'tx' field.  Only if the 'tx' field is missing, or needed to be updated, would there be a need to process the OCR XML data.

We haven't yet decided how/when OCR data will be loaded, but it won't be via Smelter as OCR data currently stored in legacy platform AIPs are being considered access data.  However it is loaded there will be a need to set a field (a date) which causes processing.

Possible new fields in ''canvas' documents:

* ocrxmldate - date when the OCR XML was last updated

Whatever tools update OCR data would also trigger the update of "updatereq" of any manifests which include this canvas.  We would need to have a _view to obtain this list.  Press, after pulling up the 'canvas' documents referenced within the 'manifest' document would also be able to detect if OCR xml data had been updated.

**Comment by RussellMcOrmond** [comment]
Relating to triggering databases....

Is the intention with administrative tools that there would be a back-end server running, or that the web client would be doing all the work?  If we intend to put OCR data within a zip file, we will need to be able to extract that OCR data from the zip.  Is this something that will be done on the server or the client?

**Comment by SaschaAdler** [comment]
Is anything stopping Smelter from loading OCR data stored in the legacy preservation system as a one-time thing? Future OCR updates would be handled by a front-end tool (as well as some back-end utility, maybe, if unzipping and figuring out where the OCR data should go proves difficult).

We do need to figure out the exact mechanism for updating OCR once we aren't loading it from the preservation platform. I assume we won't be updating OCR image-by-image, and we're going to have to make it clear that the access manifests that will be updated aren't the same thing as preservation packages.

**Comment by RussellMcOrmond** [comment]
Code simplicity is the only reason we might want to avoid that.  Keep Smelter more easily testable.

If Smelter stores the METS sequence in dipstaging, along with all the canvas noids that were allocated for the members of those sequences, then a separate tool can load the OCR data that first time.

Archivematica doesn't use the same type of IDs, but it also has the concept of a METS sequence.  It just also has the concept of a persistent identifier for the members of those sequences, something that our current preservation platform doesn't have.  Storing that array with each element being a hash (canvas noid allocated, path within AIP, persistent identifier, mets label) allows us to go back and use that as a map between the preservation and access platforms .

**Comment by RussellMcOrmond** [comment]
As to the mechanism:  My first thinking is that we will need an export from the access platform to download images by canvas noid, and then any uploading of OCR data would have the noid within it.

That upload/download can be done via a special directory (Like what Archivematica does for starting a transfer), or can be a large set of drop into the browser.  That you'll probably want to discuss with John.  Currently all that is done though SFTP from people's desktops to a server in Toronto.

**Comment by RussellMcOrmond** [comment]
Our first stage will involve a tool that pushes to 'internalmeta' in the same format it uses today, and this tool will extract the 'tx' field from the OCR XML the same as Hammer currently does.

We can revisit OCR data as we move forward with each stage.

Eventually we might be able to have Solr handle the ALTO XML directly posted to it.  (Hmmm...  https://dbmdz.github.io/solr-ocrhighlighting/ )

**Comment by RussellMcOrmond** [comment]
For when we look into this in the future, we may want to jump directly to an annotation server for canvases and not concern ourselves with the 'tx' field.  It might be that we use a simple 'tx' field to search for manifests, and then use an entirely different service for searching within manifests.


https://github.com/glenrobson/SimpleAnnotationServer

A reminder from last year's Access conference...
https://github.com/AccessLibCon/annotate which is built on https://github.com/mnyrop/annotate

This issue is related to #5 as a possible plan would be to load OCR data into the annotation server, and then extract a 'tx' like field from the annotation server.
