### ISSUE TITLE
Updating objects, in general

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#110]
There are a few questions that need to be resolved when it comes to updates performed by staff on access  objects.

1. Should these updates be triggered automatically by the admin tools, or will a staff member need to hit a big "save" button to make changes?
2. If updates are triggered automatically, should the requests to the server be granular (e.g. the "label update" only takes placed when a label has been updated) or should the entire object be updated all at once? Should the "diff" between the stored object and its changes be managed by accessor or the tool making the changes?
3. If updates are triggered manually, do operations that don't actually take place on the object directly (like updating an object's membership in a collection; see #95) need to wait for the staff member to hit the "save" button for the object?
4. Do we want to start with manual updates first, and then switch to automatic updates later? The latter seems like the long-term goal regardless.
5. Do we want to keep track of a full "StaffUpdate" (#83) for changes that can happen synchronously with the update request, like most object edits, or do we want to reserve those for changes that need to wait for a background process to complete, like e.g. DMD processing?

**Comment by RussellMcOrmond** [comment]
Systems hat:  My concern is small changes triggering multiple back-end processing of the same document (updateInternalmeta style).

Whether it is Hammer or something else in the future, we'll have processes trying to make derivatives to store in different places (including Solr), and we don't want that to happen too often.

If the desire is to save early, save often -- then store in browser storage such that a "reload" of the page will already have the information saved.

My thoughts likely provide its own simpler answer to (5) above, in that there would only be a single call to Accessor to update whatever database(s) need to be updated.


Accessor related question that is part of this:

We have thus far been using CouchDB update documents to modify data, partly to reduce over-the-wire data transmission.  With Accessor will there be a desire to regularly validate documents against a schema?  If so, then Accessor handling the update (IE: pull, update, validate, push) will be more common.   While the HTTP interface to CouchDB isn't as efficient as what CouchJS has access to, we are designing the systems side such that processes using Accessor is always on the same hardware as the CouchDB, so this is a virtual and not physical network connection.

**Comment by DivyaKrishnan26** [comment]
My thoughts to this is, though automatic updates are the end goal to be reached, starting with manual updates is a simpler thing.
**If updates are triggered manually, do operations that don't actually take place on the object directly (like updating an object's membership in a collection; see #95) need to wait for the staff member to hit the "save" button for the object?**
I have a question more than a thought for this, what are the repercussions if the operations have to wait until the big save button is hit? Is this a major factor to consider the automatic updates to start with? Are there any important operations that causes implication if the need-to- wait scenario arises?
For the (5)-To think of making the call and updating at once seems better.

These thoughts and questions are from a simpler perspective to start off with, I am not completely sure about the systems impact Russell was talking about.

**Comment by SaschaAdler** [comment]
I'm liking the idea of using localStorage to keep track of changes in the user's browser, and to have saves to the server requested directly when needed.

I'm still curious, then, about situations where the thing being updated isn't the object itself (i.e. question 3, above), but the more I think about it, the more it makes sense to incorporate those changes along with the ones to the object when saving.

**Comment by RussellMcOrmond** [comment]
There are UI questions in the client, but there is also Accessor itself.

My hope is that we can optimise CouchDB requests, and fill in Accessor object instance variables as appropriate, and have a .store() for objects to do efficient storage of objects/changes/etc.

For instance, once we have done a get on an instance variable part of a member of a collection (IE: slug), it might be appropriate to pull in more information at the same time.

I'm also wondering if we will want to have helper functions to pre-fill (IE: to do a single call for information about all members of a collection, or all canvasses of a manifest, to fill in the appropriate instance variables rather than having per-ID lookups).  Everything would still work if the optimisations weren't used, but the optimisation would be possible for developers who were able to predict what is likely to happen next (IE: if you are going to display a large list of slugs, might as well get them all at once rather than one at a time).

**Comment by RussellMcOrmond** [comment]
Can we discuss, close, or move this to become a discussion?  It is currently assigned to all of us as if we have work to do.

**Comment by SaschaAdler** [comment]
I'll either convert this to a set of more specific tasks, or move it to a discussion. Either way there are issues here that I'll be focusing on in the near-term.

**Comment by SaschaAdler** [comment]
I think I'm comfortable with where we are with these things, at least in the back-end. Let's save interface-related back-end concerns for when we have people using interfaces.
