### ISSUE TITLE
Microservice processing of Descriptive Metadata tasks

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#112]
This is largely cut-and-paste work.

We currently have a tool which, when given a file in specific formats, will output XML conforming to one of the 3 XML descriptive metadata formats we support.

* https://github.com/crkn-rcdr/CIHM-METS-App - Tool
* https://github.com/crkn-rcdr/Digital-Preservation/blob/master/xml/published/schema/2012/mets/csip.xml Description of the 3 metadata formats (Dublin Core, MarcXML, IssueInfo)

We then wrap that in a script called `wip-metsproc` which scans specific directories looking for these files, and then put the results in a CouchDB database.

* https://github.com/crkn-rcdr/CIHM-WIP

This new back-end process will pull the file from CouchDB and store the resulting XML files in CouchDB, to then be used in the access platform (as well as the preservation platform to replace.

**Comment by RussellMcOrmond** [comment]
Old ticket: https://github.com/crkn-rcdr/CIHM-Meta/issues/34
Old PR: https://github.com/crkn-rcdr/CIHM-Meta/pull/29

First part of front-end work was at https://github.com/crkn-rcdr/sapindale/pull/91 , with that work needing to be moved to the new Access admin tool  https://github.com/crkn-rcdr/Access-Platform/tree/main/services/admin


This work is dependent on finalising `dmdtask` database schema  #111 , as well as updating the front-end to match that schema.

**Comment by SaschaAdler** [comment]
See #113 for the front-end work.

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/dmd/Task.ts has the updates to the schema being planned.

`depositor` became `prefix`, but otherwise the Sapindale metadata uploader skeleton can be used for getting test data into the database.

Web interface should also need to ensure that mdType has a value before setting split{}.  A file attachment without a recognised mdType can't be used. The `prefix` can be allowed to be blank, but that might involve update to dmd/Task.ts if Slugs aren't allowed to be blank.  I'll leave all of that to the front-end developer.

**Comment by RussellMcOrmond** [comment]
@brittnylapierre ,


I have updated the title, as there may have been some confusion.  The Web interface has a front end (runs on browser client) and back-end (runs on server, using node).  The linked PR above isn't related to this ticket.

This is a separate type of service, often called a microservice, which is separate.  https://en.wikipedia.org/wiki/Microservices

In our case it uses a Queue of work that is a CouchDB view to get a list of documents that have "Work" that needs to be done.  A separate process polls for work, does the work, and updates the CouchDB document with the status.

This will be added to https://github.com/crkn-rcdr/CIHM-Meta along with other services that are part of our "Metadata Bus", and periodically run from a cron via https://github.com/crkn-rcdr/cihm-metadatabus/blob/master/docker-entrypoint.sh#L57

**Comment by RussellMcOrmond** [comment]
While I am still working on improvements, the focus is on getting additional testing done.  This will need additional help, but that will be much easier once specific features have been completed with the web interface https://github.com/crkn-rcdr/Access-Platform/issues/113 and members of the Metadata team can upload some of their own files and comment.

**Comment by RussellMcOrmond** [comment]
I'm unassigning this as there isn't work for me to do at the moment.  I am waiting for the Metadata team to provide feedback to move to DONE and close.
