### ISSUE TITLE
Adding canvases from other manifests.

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#117]
Canvases are only discoverable through the manifests they're a part of, and so adding a canvas to a manifest requires having a manifest in which it can be found.

**Comment by SaschaAdler** [comment]
I think the flow of this might look like (importing canvases from manifest B into manifest A):

1. Resolve B's slug.
2. Display B's canvases in a modal, maybe? I'm also unsure if we need to show thumbnails, but it might be nice.
3. Select all, none, or some of B's canvases.
4. Click an "Add" button. They're appended to A's canvases list.

**Comment by RussellMcOrmond** [comment]
Also think about this in context of #88 .  

We have an "orphan" flag in a `canvas` that will be filled in by a tool which walks canvases.  We may want that boolean used in the interface in some way, possibly a virtual "orphan" manifest generated by Accessor which allows staff to browse and do something with these orphan canvases.  We could even create a 'trashcan' virtual manifest, so the same tool used to manage real manifests would be used to trash unused canvases.
