### ISSUE TITLE
Approval, availability, and takedowns

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#13]
Our current platform design has one flag for whether or not something shows up on the website: `approved`. With things getting a bit more complicated, we have three availability concepts to wrangle:

* whether an access object is "done", and future breaking changes require a new version of the object (new NOID, etc)
* whether an access object is ready for public viewing
* whether an access object has been taken down for rights reasons

It seems to me that we'll need at least two flags: `approved` for whether the object is "done", and `available` for whether the object should appear online.

If/when we need to take an entire manifest down, we need a policy on how that affects canvases that belong to both the offending manifest and other ones.

(adding @nataliemacdonald, and I'm sure we'll talk about this in our rights meeting)

**Comment by RussellMcOrmond** [comment]
With the separation between preservation and access, do we need to keep objects in the access platform which we are not providing access to?  I guess I would have assumed "taken down" was a delete operation.

We didn't have this concept in the past, as we didn't have P-A separation.  Not 'approving' an AIP meant that this AIP ID and all components didn't exist in cosearch and copresentation, effectively acting like a "delete" (all couch documents relating to an unapproved AIP ID were deleted).

Question is:  Do we store previously allocated noid's in 'dipstaging', and allow an operation to re-smelter a previously deleted canvas?  Do we want that concept for other reasons as well?

I'm wanting there to be some link back to the preservation platform from the access platform, such that any relationships between preservation objects and access objects can be maintained (and backed up, eventually exposed to patrons, etc).

**Comment by RussellMcOrmond** [comment]
e162210d923351e0732f963172404a19cd8246b4 and e621a3c86f1f3e32643655590f37e7ebd3a39a1e includes the "public" field for a canvas and manifest, which is the answer to this specific question.

Should we close this issue?

**Comment by SaschaAdler** [comment]
Yeah, we sorted this out in our discussions.
