### ISSUE TITLE
Redirecting and retiring slugs.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#14]
There are times when a wrong slug was used, and staff will want to change it.  Ideal is if the old slug can redirect to the new, so that any links to the old slug still work.

Example:

http://www.canadiana.ca/view/oocihm.991573 should have been http://www.canadiana.ca/view/oocihm.9_91573

We will also want to have a way to know when a slug was, but is no longer active.  Our processes that gateway between the new access data to the old will need to know when to clear out a slug from internalmeta,cosearch and copresentation.

**Comment by RussellMcOrmond** [comment]
@SaschaAdler discussed this issue earlier today, and an update to https://github.com/crkn-rcdr/Access-Platform/blob/master/Databases/schemas/slug.json is pending.

**Comment by SaschaAdler** [comment]
We have the concept of `slugAliases` in the manifest and collection dbs for this.
