### ISSUE TITLE
HAProxy error pages

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#16]
Since we're not using Apache for proxying CAP any more, we need a new place to put generic server error pages.

We might also want to add one for 403 errors as we're currently denying access to certain Cantaloupe URLs. Different status codes need different error pages because HAProxy makes you write the entire HTTP response in the file, headers included, but I think I'll keep the text the same.

I'll update the Apache error pages with the new Canadiana design. I'll also try to get everything in the one HTTP request, since that seems to be how HAProxy handles this.

**Comment by RussellMcOrmond** [comment]
The Apache at https://github.com/crkn-rcdr/cap/tree/master/apache has errors for 500 and 503.

The only external requests that could generate those errors are proxies to CouchDB for cdn.canadiana.ca.   I believe out intention is to decommission that domain in favour of static files given we aren't authoring a content management system that allows staff to upload files.

Should we generate a ticket to clean up our usage of that domain, and put all our static files still used somewhere else?

https://upholstery.canadiana.ca/_utils/database.html?cdn  has 10 documents, and I suspect many of the files are no longer referenced by anything.

Well -- had 10 documents -- I just deleted cdn/cantaloupe , cdn/n41

**Comment by SaschaAdler** [comment]
See https://github.com/crkn-rcdr/Access-Platform/commit/dbb1e83d5b5fbe21d35ec204184dc34bc449a881

I'll ensure all remaining cdn.canadiana.ca URIs go away as part of the CAP rebrand branch, but feel free to generate an issue to remind me. All new static files are just going in `CAP/root/static`, as per usual.
