### ISSUE TITLE
Change 'pnpm run dev:up:watch' to 'pnpm run watch' which just runs docker-compose logs -f

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#180]
One of the benefits to starting docker-compose in detach mode is that you don't have to worry about accidentally hitting Ctrl-C and bringing the whole thing down.
Maybe we should add a watch script which just runs docker-compose logs -f.

**Comment by SaschaAdler** [comment]
Got this in #188.
