### ISSUE TITLE
Remove $in query from lapin-router routes

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#181]
Sadly, using $in causes CouchDB to scan through the entire index, instead of picking out the values in the provided array, which is why we have a JavaScript view set up to do this. That said, we should just add something in couch-utils that simulates what this should be doing.

**Comment by SaschaAdler** [comment]
I'll be writing a few utility functions in #182 that will help with this sort of thing.

**Comment by SaschaAdler** [comment]
#182 is merged and so I'll close this. I don't think we're using `slug.resolveMany` yet but we'll need it for the preservation import tool.
