### ISSUE TITLE
lapin health check

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#201]
`GET /` should produce output that indicates whether any of the services lapin connects to is having a hard time. Something like:

```ts
type HealthColor = "RED" | "YELLOW" | "GREEN";

interface ServiceHealth {
  color: HealthColor;
  message?: string;
}

interface LapinHealth extends ServiceHealth {
  services: {
    couchdb: ServiceHealth;
    noid: ServiceHealth;
    image: ServiceHealth; // identical to CantaloupeHealth
    // etc
  }
}
```

with more services added as we add to lapin.

We might want the HTTP request to produce some kind of 500 error if things aren't all `GREEN`, so that tools like [wait-on](https://www.npmjs.com/package/wait-on) can be used to delay starting things that depend on `lapin` until everything is ready.

**Comment by SaschaAdler** [comment]
We can also create an endpoint in the admin tools that forwards requests to this.

**Comment by RussellMcOrmond** [comment]
Ideal for the systems team is if the same format used by Cantaloupe is used, so we don't need to write a separate plug-in.

https://github.com/crkn-rcdr/puppet/blob/main/modules/canadiana/files/utilities/icinga2/plugins/check_cantaloupe

**Comment by SaschaAdler** [comment]
> Ideal for the systems team is if the same format used by Cantaloupe is used, so we don't need to write a separate plug-in.
> 
> [https://github.com/crkn-rcdr/puppet/blob/main/modules/canadiana/files/utilities/icinga2/plugins/check_cantaloupe](https://github.com/crkn-rcdr/puppet/blob/main/modules/canadiana/files/utilities/icinga2/plugins/check_cantaloupe?rgh-link-date=2021-07-29T14%3A51%3A15Z)

That's what I was going for, but I didn't have Cantaloupe running to check its output. Cantaloupe's output looks like this, right?

```ts
type CantaloupeHealth = {
  color: "RED" | "YELLOW" | "GREEN";
  message?: string;
}
```

What about something like

```ts
type HealthColor = "RED" | "YELLOW" | "GREEN";

interface ServiceHealth {
  color: HealthColor;
  message?: string;
}

interface LapinHealth extends ServiceHealth {
  services: {
    couchdb: ServiceHealth;
    noid: ServiceHealth;
    image: ServiceHealth; // identical to CantaloupeHealth
    // etc
  }
}
```

which can let a script do a deeper dive on which service is causing trouble, or ignore `services` and do the same as the Cantaloupe health check plugin does.

`AdminHealth` can read from the lapin health output and create a similar structure, including `lapin` in `services`.

**Comment by RussellMcOrmond** [comment]
For those of us with the VPN access, http://cheddar.uab.c7a.ca:8182/health

The above looks good.
