### ISSUE TITLE
Create back-end code for removing slugs ('putting objects into storage')

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#211]
This will require a special route and shouldn't be something you can do by zeroing out the slug input in the editor. 

There should be an AccessHandler method that accepts a noid (and the User?) and:

- [ ] Looks up the noid in the members view
- [ ] Runs an update function on each Collection found in the lookup that searches through the Collection's members list and removes the entry with the noid as the id, then updates updateInternalmeta
- [ ] Runs an update function that removes the slug from the object identified by the noid and updates updateInternalmeta

**Comment by SaschaAdler** [comment]
If possible, can we not use "putting objects into storage" as the metaphor for what's going on here? We have multiple repositories where data is "stored" and I don't want the concept of "storage" overloaded too much. I think either "Unassign this slug" or "Free this slug" is more appropriate.
