### ISSUE TITLE
Load all "tag" collections into cap_collections (labels, summary)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#22]
A full list of collection tags used on any page or title (series or monographs) can be seen with views:

https://admin.canadiana.ca/couchview/internalmeta/tdr/colpages?group=1&reduce=true
https://admin.canadiana.ca/couchview/internalmeta/tdr/coltitles?group=1&reduce=true

As we are making collections out of these tags, the tags that exist in the 'cap_collections' database will have English and French labels, but the tags not in that database will have {} as the label.

Do we want to pre-load cap_collections with all tags so that we will have proper labels?

**Comment by RussellMcOrmond** [comment]
https://upholstery.canadiana.ca/couch/_utils/document.html?collection/69429%2Fs0q52f767c19 is an example..  This is https://upholstery.canadiana.ca/couch/_utils/document.html?slug/restricted


We don't have a view on the 'slug' database to look up what slug that matches, but I have a function in loadseries that works for the moment.  We may want to spec out some views we want on these databases as well.

**Comment by RussellMcOrmond** [comment]
I added a feature to the 'loadseries' tool to check for tags that are missing in the 'slug' database, and found: gmma , dfaitnottogoonline , omcn , qmma , restricted

**Comment by RussellMcOrmond** [comment]
This was previously discussed in #20, which we've decided to move forward with.

**Comment by SaschaAdler** [comment]
I'm not sure what to do with the five tags you have listed above. I suspect some of them will never make it to the access platform (like `dfaitnottogoonline`!).

**Comment by RussellMcOrmond** [comment]
I guess this is more a question for Beth to answer now that we have decided that collections not already created in cap_collections won't be transferred over to the new platform.
