### ISSUE TITLE
Determine production deployment policy

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#223]
Good news, everyone! The production deployment builds.

The production deployment policy could just be that I build an image, tag it with today's date, push it, and then create an issue in the relevant repo to get the tag updated where it needs to be. There are a couple of problems with this:

1. I'm not always around when updates need to be pushed
2. Other developers don't have access to the relevant repo
3. We might want to push multiple images on the same day without overwriting earlier ones (in case we need to revert a bug)
4. Maybe having to edit files to use the latest production image tag is annoying?

Some solutions to things here that may or may not be problems:

1. All developers get access to issue creation in the relevant repo
2. I write a little script for production deployment which tags the production image with both the latest abbreviated Git commit hash and `latest`, and then push both of these tags to our Docker registry. Anyone can run this script.

Thoughts on this?

**Comment by RussellMcOrmond** [comment]
Issue creation doesn't need to be in the "relevant repo" (private), only tagged with the relevant people (A member of the systems team).  This repository is an appropriate place to generate issues for deployment of Access Platform software.

That "relevant repo" is there for systems team members only, and you are personally an honorary systems team member (The 2'd backup for when Hugo and I are both unavailable).  You do not have access to it related to your position as application lead, and it is not a repository for software developers.

Updates to production should be done by Systems staff, with an adequate test procedure in place to ensure that proper testing is done of any updates.


We aren't anywhere remotely near CI/CD, so a script or process that anyone other than a systems person can initiate is inappropriate at this time.  We can revisit that concept at a much later date, and isn't something that is part of "The Split".

**Comment by SaschaAdler** [comment]
Ok, happy to bug people in https://github.com/crkn-rcdr/Systems-Administration when things need to be updated.

The script just pushes already-built images to the Docker repository. It's something I'm already doing before I alert any sysadmin to changes. I agree that we aren't ready for developer-invoked scripts that actually redeploy changes to production.

I'm not going to push anything to our Docker registry until we have a naming scheme for our image tags, though.

**Comment by RussellMcOrmond** [comment]
I'm a fan of image tags that give a hint of the date (oops, that is old), but given Git commit hashes are easy to look up that works as well.  Pick whichever you wish, and the Git history will provide us the necessary information to "go back in time" if a recent Docker image isn't working/etc (Although, git revert is usually all we need do to for the puppet config).

The script you mention could output something to cut-and-paste into a GitHub issue as a bit of a "form letter to systems" if that makes things easier.

**Comment by RussellMcOrmond** [comment]
Re: "Maybe having to edit files to use the latest production image tag is annoying?"

We want to use puppet for everything, and avoid ever having changes made to any of the production servers that isn't in the Git history.  So, changing the tag to be different is a requirement for the new version to be pulled.  A changed name is a trigger for restarting of containers, etc.

**Comment by SaschaAdler** [comment]
Ok, I'll avoid `latest` and only use the Git commit hash. (I'd have liked using something like an ISO 8601 timestamp, but I'd then have to mangle all of its colons. I could give that a try instead if you want the tags to be sorted by date. Ha, I could use both.)

When the first image is pushed I'll create a Systems-Administration issue.

**Comment by RussellMcOrmond** [comment]
BTW: For the docker registry,  multiple tags can be applied to the same image by pushing the image with multiple tags.  They are all just aliases.  So, push as many aliases as you think are useful, but we'll just use one of them (the one that will always be different) for production pulls.

**Comment by SaschaAdler** [comment]
See the above PR for the image deploy script.
