### ISSUE TITLE
Contrast between selected and other SideMenu tabs is difficult to parse

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#224]
Could just be me, but I'm having a hard time telling which one of these tabs is the selected one:

![side-menu-](https://user-images.githubusercontent.com/26656905/128777220-1755d2a7-6b3c-400f-9a9c-4845410fcf1a.png)

(It's `General Info`.)

We could instead have tab selection indicated by the primary Canadiana teal (TM) as the background colour and white as the text colour, for example. Whatever makes sense the contrast between the two possibilities needs to be greater on the whole. I can't tell that clicking on these necessarily does anything.

**Comment by brittnylapierre** [comment]
Hey @SaschaAdler I'll see what teal looks like. I'm wondering if you would like the table row hover contrast increased too?
![Screenshot from 2021-08-11 11-43-36](https://user-images.githubusercontent.com/10541019/129060851-906f0136-177d-467b-91ba-4d3c2a401873.png)

Thanks!

**Comment by SaschaAdler** [comment]
The rows are fine. The problem with the tabs is that they're interactive, and it's hard to tell how.
