### ISSUE TITLE
Dmdtask: Copy XML to Access and/or Preservation platform storage.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#227]
See [Documentation in Sharepoint](https://crkn.sharepoint.com/:w:/s/platform/EW2AmkBTXZZEnwWWSAsIHDcBlRWSAYf9gL3oKPrvr4EU0A?e=Xq5kvk) for details.

The last stage of the process is to copy the set of XML files into the platforms.

* For the existing Preservation platform, these are dmd.xml attachments to the documents in the `wipmeta` database.
* For the new Access platform, these are dmdTYPE.xml files stored in Swift

As there is no further processing of the XML at this point, only storage, we have the option of doing this work within `admin` and `lapin` rather than doing it in Perl.

Note to @SaschaAdler  :  You moved the storage policy file via https://github.com/crkn-rcdr/Access-Platform/commit/0e5ca5d8654cb907566e33e3fc9c053246e1b8a9 , and then removed Accessor.  We probably want to get that documentation back  :-) .  I wanted to link to it in this issue, which is why I noticed it went missing.

**Comment by SaschaAdler** [comment]
See #231.

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond Sascha told me to implement the label portion for the access update. Right now, the label gets updated in the "access" database when someone updates the metadata in access. Is there a label key for the object in wipmeta that needs this to be updated too? Or is it just handled by the update to dmd.xml? Thanks!

**Comment by RussellMcOrmond** [comment]
I made my notes in a different ticket https://github.com/crkn-rcdr/Access-Platform/issues/259#issuecomment-915209832

Yes, label is part of both access and preservation.
