### ISSUE TITLE
dmdtype for 'cap_collections' collections?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#23]
Currrently dmdType in https://github.com/crkn-rcdr/Access-Platform/blob/master/Databases/schemas/collection.json is marked as both mandatory, and has only "dc" and "marc" as values.

Collections which come from tags or cap_collections don't have descriptive metadata, so we'll need to decide how to support that.

**Comment by RussellMcOrmond** [comment]
I see a couple options:

* Not defined has meaning, with field not being mandatory
* Value of "none" is added, which has meaning
* (ugly IMO) a dummy DC record automatically created.

Any other thoughts appreciated.

**Comment by SaschaAdler** [comment]
We should go with one of the first two, but I don't have a preference.

**Comment by RussellMcOrmond** [comment]
How about if you make it optional, and we can define somewhere what being blank means (so tools will know what to do in that situation).

When creating new manifests with the new web tools there may also be a period before a descriptive record is loaded, which means dmdType should be optional for `manifest` as well.
