### ISSUE TITLE
couch-utils attachment methods

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#240]
DatabaseHandler needs `getAttachment` and `uploadAttachment` methods for DMDTask processing.

**Comment by SaschaAdler** [comment]
I'm not really going to have a way to test these without doing some of the DMDTask work. @brittnylapierre I can take on the `dmd.new` back-end stuff also; I don't think we have an issue for it yet.

**Comment by brittnylapierre** [comment]
@SaschaAdler Ooo sure! I juuust started on it in my branch but I'm 100% sure you'll be able to do it quicker! Here's my branch for the dmd.new: https://github.com/crkn-rcdr/Access-Platform/pull/238
