### ISSUE TITLE
Dmdtask:  Update CouchDB design documents (views and updates) to match current spec

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#246]
Now that I believe https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/dmd/Task.spec.ts is more firm, we can update https://github.com/crkn-rcdr/Access-Platform/tree/main/services/couchdb/dmdtask/design/access to match.

Needed by #113 and #112

**Comment by SaschaAdler** [comment]
I'll also update the schema to return one of ```"dc" | "issueinfo" | "marc"``` as `outputType` in ParseRecord.

I might take this opportunity to change the name of `mdType` to `inputType`, partially because the discrepancy between `dmd` and `md` is bugging me.

(we could also get rid of `Type` in both field names?)

**Comment by RussellMcOrmond** [comment]
> we could also get rid of Type in both field names?

Yes.  Whatever makes it more obvious to developers that one is about the user telling the parser something about the upload, and the other is the parser telling the user something about what it found.
