### ISSUE TITLE
Update CAP to handle PDF downloads from new Swift container

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#277]
This is the CAP side of #137 

How things are stored in Swift currently documented in #231

The container should be configurable (Currently: /v1/AUTH_crkn/access-files )

$noid can be canvas (single page PDF) or manifest (multi-page PDF).

At this time we only need to handle $ext="pdf" files.  Other possible downloads should be left to a later date.

Note: During data migration, CAP will need to support downloads from both the Preservation container (Currently  preservation-cihm-aip ) as well as the access-files container.  The metadata record available to CAP needs to be clear as to which is currently available.  Old paths will still work after the file is copied, so we don't need to worry about an issue during the transition.

**Comment by RussellMcOrmond** [comment]
@SaschaAdler 

The code in Hammer2 doesn't currently do anything with the `extension` field in `master` or `ocrPdf`.   You will likely want something to indicate to CAP that a file exists within the access-files container.

Please let me know how you would like to handle this in `copresentation` documents for now (knowing we will be replacing that database in the future).


https://github.com/crkn-rcdr/CIHM-Meta/blob/5ed31efa8fdb575aaf0027e81eb22b57fe296ffd/lib/CIHM/Meta/Hammer2/Process.pm#L265-L291

**Comment by RussellMcOrmond** [comment]
In [cosearch-copresentation](https://crkn.sharepoint.com/:x:/s/platform/Ed9hL3v-q_xMr9XGgMAd9s0BCC5FQbO08tyb7Zlvv3viCw?e=Hh50Mz) spreadsheet we have the following relevant fields:

```
canonicalMaster
canonicalMasterSize
canonicalMasterMime
canonicalMasterMD5
canonicalMasterWidth
canonicalMasterHeight

canonicalDownload
canonicalDownloadSize
canonicalDownloadMime
canonicalDownloadMD5
```

Where `canonicalMaster` is replaced, we could have `canonicalMasterExtension`
Where `canonicalDownload` is replaced, we could have `canonicalDownloadExtension`

Let me know if this is sufficient for now, and I'll make the changes to Hammer2 and Press to handle the two new optional fields (and ensure the other two are optional, and nothing will break when they are missing).

**Comment by SaschaAdler** [comment]
Is `canonicalDownloadExtension` ever going to be anything except `pdf`? That's fine for now, I guess.

**Comment by RussellMcOrmond** [comment]
I do know with the current fields that CAP doesn't like things https://www-demo.canadiana.ca/view/oocihm.8_01672_3

**Comment by RussellMcOrmond** [comment]
I wanted to find an example of an canvas fully copied, with both pdf and image.  Found a random PDF via SwiftStack clients, looked up the CanvasID in manifests, and found.

https://parl-demo.canadiana.ca/view/oop.com_CDC_3302_5_4/97?r=0&s=1

Pages around it have the PDF, that page is missing the PDF because it doesn't have the canonicalDownload field.  Surprised there wasn't an error as http://iris.tor.c7a.ca:5984/_utils/index.html#database/copresentation2/oop.com_CDC_3302_5_4 is also missing canonicalMaster for  oop.com_CDC_3302_5_4.97


Note: Next and previous page links were odd, and kept the same status as the previous page with whether to show a PDF download icon.  Only when I hit reload did it seem to look at the page I was actually looking at to determine if a PDF download icon should be placed.

**Comment by RussellMcOrmond** [comment]
docker.c7a.ca/cap:20210915 is on the demo sites, for further testing...

**Comment by RussellMcOrmond** [comment]
Confirmed with https://www-demo.canadiana.ca/view/oocihm.8_01643_1/1?r=0&s=1 that was recently Smelt'd that CAP works with the new container for both image references and single page PDF downloads.
