### ISSUE TITLE
Databases/schemas/_util.json legacyRepoURL constant.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#28]
There will be times when we will want to point to a different Swift server to access the LegacyRepo.  For Cantaloupe ID's we also don't include the Swift prefix, but only the path within the container.  

Using the same for legacyRepoURL and removing the constant "^https://swift.canadiana.ca/v1/AUTH_crkn/repository/" from the definition seems appropriate.

Example:
`{   "legacyRepoURL":  "oocihm.8_00006_5/data/sip/data/files/7690.jpg" }`

**Comment by SaschaAdler** [comment]
I'll make this change but I'll also change the field name from `legacyRepoURL` to `legacyRepoPath` since it won't end up being a full URL.
