### ISSUE TITLE
Staff training and tool evaluation.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#280]
This is the final step in "The Split", where @jjfriedman and team evaluate and use the tool, and confirm everything is sufficiently finished for us to flip the switch and make the -demo sites into the live sites used by patrons.

**Comment by RussellMcOrmond** [comment]
Once @brittnylapierre confirms, and we have done additional testing in production, the Descriptive Metadata Loader should be ready for other staff to check out.

We will want to highlight that the tool can be used for both Preservation (to replace sticking files in specific directories) as well as the new Access platform (where changes should be visible online fairly quickly after they submit the changes).

I'm guessing that Brittny will be doing the demonstration/training/etc?

I believe what was decided at past meetings is that documentation for other teams would be managed by those other teams, with us providing input as requested by them.

---


As discussed in an earlier meeting, I will continue to launch Smelter myself using the tool in Sapindale until the new tool is ready.  I will Smelt based on the IDs I get from `loadseries` and `makepublic`.


---

If this feels like this shouldn't be an "issue", but a discussion, then @SaschaAdler should convert accordingly. @enouserid is managing a slide on Sharepoint for all the steps, so we don't need this to be in the Kanban as well.

**Comment by RussellMcOrmond** [comment]
See: [Platform Projects: Status of Deliberables](https://crkn.sharepoint.com/:p:/s/platform/ERwf-QBT6ldMnDX6Yb5m06gB2ufrVTXU8kqz1bWl39DPjA?e=woiF8L)

**Comment by RussellMcOrmond** [comment]
Confirming that @jjfriedman can see and comment on this ticket.

**Comment by jjfriedman** [comment]
Beautiful, thanks @RussellMcOrmond

**Comment by RussellMcOrmond** [comment]
This part of the project is now underway via the ["Show and Tell"](https://github.com/crkn-rcdr/Access-Platform/discussions/categories/show-and-tell) feature.

It is also being tracked via [Platform Projects:​
Goals and Deliverables​](https://crkn.sharepoint.com/:p:/s/platform/ERwf-QBT6ldMnDX6Yb5m06gB2ufrVTXU8kqz1bWl39DPjA?e=uOzAXA) (the updated title for the link mentioned above).

I suspect that is sufficient, and we don't need to track with a separate Github issue.  Please reopen if anyone disagrees.
