### ISSUE TITLE
Zod error on editor load

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#294]
https://access.canadiana.ca/object/69429/m0m901z46797
![Screenshot from 2021-09-20 10-40-05](https://user-images.githubusercontent.com/10541019/134021570-33170db9-eb1a-42b3-a944-e8073184f8c8.png)

**Comment by RussellMcOrmond** [comment]
This might be related  #293 , but I didn't confirm that this was the field that Zod didn't like.

**Comment by RussellMcOrmond** [comment]
I have since confirmed by removing the "staff" field from the relevant document and hitting reload.

**Comment by brittnylapierre** [comment]
Sounds good @RussellMcOrmond! I was adding checks for this to display an error to the user when there is one, and can add in a fix/temporary fix for this particular issue. This is happening because not all items in prod have a "staff" property?
