### ISSUE TITLE
Databases/schemas/manifest.json : 'canvases' mandatory for born digital?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#30]
Is the intention that canvases=[] when masterPages has an array of labels for born digital?

**Comment by SaschaAdler** [comment]
I've required that manifests have either `"type": "multicanvas"` or `"type": "pdf"`. Let me know what you think.

**Comment by RussellMcOrmond** [comment]
I really like that it was possible to do that.  I haven't validated the manifests or canvases I'm trying to generate yet, and may have more thoughts when I get to that stage.
