### ISSUE TITLE
Select between `ordered` and `multi-part` collections

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#307]
When creating a new collection or editing an existing on, the user should be able to change the status of the `behavior` field.

**Comment by brittnylapierre** [comment]
@SaschaAdler Does the collection member list UI need to change at all for any of the options? 

@RussellMcOrmond  mentioned in https://github.com/crkn-rcdr/Access-Platform/discussions/305 that we are only supporting behavior=unordered, and behavior=multi-part for now. I'll just hide the other options right?

Thanks!

**Comment by RussellMcOrmond** [comment]
Looking at https://access.canadiana.ca/object/69429/s0td9n29qn02 as an example.

For `behavior=unordered`, maybe the up/down positional isn't needed (only trashcan).
The ability to move members around is only needed for `behavior=multi-part`.

Listing the behaviour in the General Info would be great (possibly where the change is made).

Hide the other options? Not sure what you are thinking here.  It might be that for other behaviour that it doesn't show up in the editor until we support that feature in some way (IE: new page viewer).
