### ISSUE TITLE
JSON Schema comes with a date-time format

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#31]
We don't need to define it ourselves. See [here](https://json-schema.org/understanding-json-schema/reference/string.html?highlight=string#id9).

**Comment by RussellMcOrmond** [comment]
Having our own subset allowed us to make assumptions about the text format which we could use in couch views.  If we allow any date-time then we will have to parse the strings as dates in order to make any comparisons/etc.

**Comment by SaschaAdler** [comment]
The date-time format is strictly ISO 8601, and so I'm a bit unclear as to what kind of comparisons you're concerned about. This would allow dates to be entered in non-UTC timezones, I suppose.

**Comment by RussellMcOrmond** [comment]
Correct -- which would disallow string comparisons to be done on the date.

Take a look at https://github.com/crkn-rcdr/Access-Platform/blob/master/Databases/design-docs/internalmeta/design/tdr/views/depositormanifestdate.js as an example of what we have been able to do with the very restricted date format.

**Comment by SaschaAdler** [comment]
We'll keep the format as is and specify in Databases/README.md the subset that is currently required to deal with CouchDB 1.7's archaic Spidermonkey.
