### ISSUE TITLE
DMD Tasks - A way to show on the page once the live site has been updated with the new metadata

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#329]
When everything is done running, after the user presses Update Descriptive Metadata:
![Screenshot from 2021-09-30 10-54-19](https://user-images.githubusercontent.com/10541019/135479291-357ac1ea-9f55-4b10-acd9-538a7cc5eeb3.png)

It would be helpful to show an indication of when the live site has been updated to show the new metadata.

**Comment by RussellMcOrmond** [comment]
I'm curious what you are thinking here.

the updateInternalmeta flag is set, and at some point in the future Hammer2 and Press will run -- only then are the presentation docs that CAP uses updated to reflect the new data.

There is an additional step with search, given search documents updated by Press then need to be streamed and indexed into Solr.   I hope in the future we will drop some of these intermediary steps and have software which parses the source data and posts directly into the various instances of Solr.  This will remain a separate step from the creation of presentation documents.
