### ISSUE TITLE
DMD Tasks - Some rows indicate success across all columns but aren't actually updated in the platform

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#330]
When running: https://access.canadiana.ca/dmd/146911304457d93adf9ee1cfc152f1a6

Producing:
![image](https://user-images.githubusercontent.com/10541019/135508150-bfa6c479-7f35-45bc-8dc6-ad891c196e7a.png)

Some of the successful rows changes were applied, and some weren't. Ex: 8_00214 indicates success but the changes were never seen on the demo site.

It was run around 10am EST Thursday Sept 30th.

**Comment by nataliemacdonald** [comment]
If you look at the 650 fields in the preview you can see the updated subject headings that should have been processed.

**Comment by RussellMcOrmond** [comment]
Suggestion is to make sure you are not sending all these update requests at the same time, and overloading one of the services.  You will want to use a Semaphore to limit the number of concurrent requests.

As an example, check out:  https://github.com/crkn-rcdr/CIHM-Meta/blob/main/lib/CIHM/Meta/Smelter.pm#L159-L177

There are many libraries on npmjs.com that may be appropriate, so you don't need to roll your own:

* https://www.npmjs.com/package/semaphore
* https://www.npmjs.com/package/await-semaphore
* https://www.npmjs.com/package/semaphore-async-await
* https://www.npmjs.com/package/promise-limit

**Comment by brittnylapierre** [comment]
Awesome! Thank you Russell!
