### ISSUE TITLE
Generating manifests from DB/Text records (referencing existing canvases)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#339]
People from Heritage Services have been creating records which they want to be able to automatically create manifests from.  They are subsets of other manifests, so are made up of references to existing canvases.

I will attach a sample of a CSV I was sent.  The editing is being done in DB/Text, so we can receive the data in XML format from the database as well.

We will want to get more specific about the design first before implementing. I wanted to create this ticket so that that the work could be scheduled and assigned once resources are available, and we had a place to collect more information.

[N_00117 Colonial farmer.csv](https://github.com/crkn-rcdr/Access-Platform/files/7315712/N_00117.Colonial.farmer.csv)

Cc: @BeS4 @jjfriedman

**Comment by RussellMcOrmond** [comment]
Question for @enouserid ,

Rather than an issue in GitHub, should this be documented and scheduled as a project?  You could add that to your documentation, and we could remove this issue from any Kanban.

**Comment by brittnylapierre** [comment]
(Re-opening so I don't forget about this information)
