### ISSUE TITLE
should ocrPdf support legacyRepoPath and stored in access_files?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#34]
For a 'canvas' and a 'manifest' document there is an ocrPdf field which has path and size pointing to a legacy repo.

In the future we will be storing PDF's generated from OCR directly within the access platform, as we are doing right away with the XML files (ocrType is only a string indicating the type of xml file).

They would be stored in /v1/AUTH_crkn/access_files/$noid.pdf  (where $noid is a manifest or canvas noid).

How do we want these alternative locations to be referenced?

**Comment by RussellMcOrmond** [comment]
We also discussed only supporting single-page OCR PDFs, with the multi-page PDF's referenced in a manifest always being a derivative.  Do we want to implement this right away, and split the multi-page PDFs before any copy to the P-A split access platform?

**Comment by SaschaAdler** [comment]
Yes, we want to implement this right away.

Another `update` will be added to handle the forthcoming tool that will generate multi-page PDFs from single-page PDFs (and vice versa).
