### ISSUE TITLE
Making slugs mandatory.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#350]
@SaschaAdler has indicated a desire to make slugs mandatory.

Allowing manifests to exist without a slug was conceived to support a feature which I don't believe we need to offer, at least not at this time.  The idea was to have the access platform remember (and allow you to browse) the past history of a given manifest (IE: all "versions" of manifests would be remembered).

There is the CRKN assigned transparent identifier, and there is a platform (automated) assigned opaque identifier.  The CRKN assigned identifier is merely a unique field in CouchDB, but in order to change/remove/etc the opaque identifier you need to (re)move other data with it (currently only in Swift, but may be other data using those opaque identifiers).  Swift doesn't have the concept of "rename", so moving data to a different identifier involves copying/deleting objects.

The general issue is discussed in #347.

We have not yet authored a "walk" to verify that all Swift objects have a corresponding record in CouchDB (and vice versa).

We currently have many manifests without slugs, which a simple view can expose.  They have been created as part of the re-smelting that is needed, as the old manifest needed to have the slug unassigned in order to smelt the update.

Using the following Mango Query I found there are 401 entries in the `access` database without a slug so far.

```
{
   "selector": {
      "slug": {
         "$exists": false
      }
   },
   "fields": [
      "_id"
   ]
}
```

Note: As a quick transition I can author a tool which assigns a machine generated slug (noslug with a unique number appended), and staff can then easily look up these noslug manifests and delete them.  They will easily be unique, as the rest of the slugs conform to the CIHM ID assigning convention of having a "." in the ID.

Also: That "." has meaning to staff, but should't have meaning to us any more.  It's not depositor.identifier in the Access platform.

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/Systems-Administration/blob/main/data-tools/bin/access-noslug

This tool looks for access objects that don't have a slug, and attempts to remove them correctly (removing associated Swift objects).

Checking with @brittnylapierre and @SaschaAdler , but I believe that having the delete button on the interface do this deleting internally was the remaining work for this issue.  Did https://github.com/crkn-rcdr/Access-Platform/issues/425 complete this work?

**Comment by RussellMcOrmond** [comment]
I recommend ignoring the {type} field.  Check if the fields for the relevant Swift object exists, and deleted if they do.  That way you don't need to worry about whether a given Swift object might exist for a given Access object type -- the field existing tells you that.

* $thisdoc->{file}->{extension} 
* $thisdoc->{ocrPdf}->{extension}
* $thisdoc->{dmdType}

Alternatively you can just try to delete all 3, with a 404 being a valid response.  You won't ever delete something you shouldn't, as the OID for the document is ...  well... opaque and unique.  Looking first is more efficient, which will be relevant if you want to use this code for bulk deletes rather than one-off from a web interface.

What I wrote was from back when we only had collections and manifests, and there was really no reason for me to look at the type for access objects.  It would be an issue for canvases, but that is an entirely separate database.

**Comment by brittnylapierre** [comment]
@RussellMcOrmond I think that this can be closed now if the deletion logic was the last step :)
