### ISSUE TITLE
none vs @none

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#37]
It seems like the JSON-LD spec (and therefore IIIF Presentation API v3) likes "@none" instead of just "none" for indexes where the key isn't known. I guess they had settled on "none" only long enough for us to use it in our schemas. Should we switch back to "@none", or should we use "none" internally and map it to "@none" for cached IIIF documents?

**Comment by RussellMcOrmond** [comment]
I'm a fan of using IIIF specifications wherever possible.

Us writing a tool to go through current CouchDB documents and change "none" to "@none" isn't that hard, and data cleanup of our demo data is kinda expected at this stage of the process.

If you can generate me  a ticket with all the places where this changes, I can update Smelter and the collection loader tool appropriately.

**Comment by SaschaAdler** [comment]
According to the just-published [final version of the spec](https://iiif.io/api/presentation/3.0/#44-language-of-property-values), we're back to just `none`. I'm not sure what I was reading two weeks ago. :stuck_out_tongue:
