### ISSUE TITLE
Check up on the glossary

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#376]
Two things immediately come to mind:

1. Noid/slug semantics
2. We should define "smelting" (requested by @jjfriedman)

**Comment by RussellMcOrmond** [comment]
I had a quick glance at: https://github.com/crkn-rcdr/Access-Platform/blob/main/Glossary.md


We might want to make clear ideas which are future facing, and which will be relevant to the tool that are being finished up as part of [The Split](https://github.com/crkn-rcdr/Access-Platform/projects/1).

Examples:


* A manifest can only be a member of a single ordered collection (Legacy metadata bus, treated as "series", etc)
* Takedowns won't exist at a per-image level, only unpublishing of a manifest.
* Text values will only support the "none" language (Metadata bus Hammer/Press, as well as CAP and Solr).


We can decide that "Smelter" is the code-word for some software, and that this term not be used in documentation or user interfaces like Sapindale was something only developers knew about.

Under "Canvas" the following text already exists: "When an image is imported from preservation, a canvas is created with the imageʼs dimensions, with the original image painted on the canvas as an annotation."

Creating canvases of this type (single image canvases, not any other type of annotation or complexities at this time), and creating a manifest pointing to these canvases (in the order they existed in preservation), is what that tool does.

But we can just call that "import from preservation" in all the staff interfaces, and not worry about the term "Smelter".

Once a manifest with a specific transparent identifier (slug) is created thought "import from preservation", it isn't special compared to any other manifest. Calling it an "archival manifest" as was previously suggested made it seem like it remained special after it was created.


I believe it is useful for us to clarify NOID as "Nice Opaque IDentifier", and to discuss opaque vs transparent identifiers.  There is a reason we need each at different times.

**Comment by RussellMcOrmond** [comment]
Alerting @brittnylapierre and @DivyaKrishnan26 to this issue.  This could be converted to a discussion if that makes  more sense.
