### ISSUE TITLE
Update Metadatabus to support "PDF" style Access documents

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#384]
https://numeris-demo.canadiana.ca/view/numeris.RD_2004_FA00_013
Has missing information in http://iris.tor.c7a.ca:5984/_utils/index.html#database/copresentation2/numeris.RD_2004_FA00_013
(Order and components missing -- a Hammer2 issue?  will find out).

https://numeris.canadiana.ca/view/numeris.RD_2004_FA00_013
http://iris.tor.c7a.ca:5984/_utils/index.html#database/copresentation/numeris.RD_2004_FA00_013

**Comment by jjfriedman** [comment]
To clarify, is this only *new* born-digital PDFs or existing ones as well?

**Comment by RussellMcOrmond** [comment]
Both.

We have some existing born digital PDFs in the Numeric project that won't work on the new access platform unless/until we add that functionality.  An example is provided:

* New Access demo: https://numeris-demo.canadiana.ca/view/numeris.RD_2004_FA00_013
* Legacy access we are trying to decommission: https://numeris.canadiana.ca/view/numeris.RD_2004_FA00_013


We also don't have adding new born digital PDFs (or anything other than images) in the roadmap for the new/transitional access platform, so if we temporarily add support for those legacy PDFs they will be the only ones that work until we add that new functionality to Archivematica and related tools (if such a feature is needed).  The ability to ingest those born digital PDFs was temporarily hacked into the preservation platform to fulfil the requirements of that project, and that ugly hack was since removed.


We want to keep new and/or unnecessary features to a minimum in order to allow our technology transformation to happen smoothly, and I'm trying to determine if born digital PDFs is a feature that we need to support in the platform during this transition.

**Comment by RussellMcOrmond** [comment]
Note to @DivyaKrishnan26 and @brittnylapierre ,

This work isn't yet scheduled, but I thought I'd make you aware of this issue.

I put "numeris.RD_2004_FA00_013" into the lookup at https://access.canadiana.ca/ and got to https://access.canadiana.ca/object/69429/m0028pc2tf1g

Changing slug and label, unpublishing and deleting are the only things that can be done.  There is an error in the console: Cannot read properties of undefined (reading 'length')

The "Manage Content" tab should probably not be enabled, as adding a canvas would likely cause everything to break (only from="canvases" can have the `canvases[]` array, while from="pdf" has a `pageLabels[]` array).

I don't know if there is a need to be able to edit the page labels for the PDF files.  That could be a future feature request, if ever needed.

**Comment by RussellMcOrmond** [comment]
Staff wanting to see a full list of manifests representing born-digital content can view: 
https://admin.canadiana.ca/couchview/access/tree/pdf?group=1&range=false&reduce=true

The ones marked "file" are the born digital -- currently 738 manifests, all Numeris ID's.

**Comment by RussellMcOrmond** [comment]
Specs cleaned up as part of https://github.com/crkn-rcdr/Access-Platform/commit/2b99d5354ef6be330f14c9289882b95e1ceb851d

**Comment by RussellMcOrmond** [comment]
Based on some chat earlier today with @SaschaAdler and @brittnylapierre and https://github.com/crkn-rcdr/Access-Platform/issues/407#issuecomment-998848171 , I'm wondering if we want to handle this differently than "repeat the past".

* Should we drop the "pageLabels" field from https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/access/Pdf.ts
* Should we no longer generate "page" level documents in `cosearch2` or `copresentation2` ?
* Is the `copresentation2` document listed above close, with the following updates?
  * We don't generate `components` or `order` fields, rather than the current of an empty array and an empty hash.
  * We add `component_count` and fix or remove `component_count_fulltext`.  The existence of a count rather than an array of components becomes an obvious way to detect between the formats.
* For `cosearch2`, we can have `Hammer2` extract the data for the `tx`, `component_count` and `component_count_fulltext` fields:
  * Old: http://iris.tor.c7a.ca:5984/_utils/index.html#database/cosearch/numeris.RD_2004_FA00_013
  * New: http://iris.tor.c7a.ca:5984/_utils/index.html#database/cosearch2/numeris.RD_2004_FA00_013
* CAP be updated to do something smarter.  It can offer a PDF viewer and download option, and then if we get a request to offer a similar UI we can handle that at a later time?

**Comment by RussellMcOrmond** [comment]
TODO: Smelter should copy the PDF rather than providing reference to the PDF in the preservation files.  This will require that we coordinate and implement something in copresentation documents to pass FileRef type information as `canonicalDownload` only works when the files is in the preservation-files Swift container.



numeris.TV_2008_SU00_001 was re-smelted, and I have been using it for testing.

* https://access.canadiana.ca/object/69429/m0sf2m61h62n  has expected error as type="pdf" isn't supported in the editor yet.
* https://numeris-demo.canadiana.ca/view/numeris.TV_2008_SU00_001 has an error (without stderr logging, which was unexpected) due to lack of `components` and `order` fields which isn't supported yet (Number of pages in PDF is in `component_count`).

**Comment by RussellMcOrmond** [comment]
I wouldn't mind some feedback on the following documents to confirm they are as expected, so I can merge https://github.com/crkn-rcdr/CIHM-Meta/pull/56

* http://iris.tor.c7a.ca:5984/_utils/index.html#database/cosearch2/numeris.TV_2008_SU00_001
* http://iris.tor.c7a.ca:5984/_utils/index.html#database/copresentation2/numeris.TV_2008_SU00_001

We could decide on what to do with `canonicalDownload` when the files are in `access-files` earlier, or leave that alone for now.

**Comment by RussellMcOrmond** [comment]
The metadatabus work has been merged, as with the CAP updates.

The metdatabus updates have been deployed to production.
