### ISSUE TITLE
Move slug information from separate slug databases

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#39]
Currently manifest and collection slugs are in a separate 'slug' database.

@SaschaAdler and I discussed putting the information within that database (_id, aliases) within manifest and collection documents, using a couch view for lookup by slug.

The schema will need to be updated, and a plan for updating any tools, APIs, and already stored CouchDB data.

**Comment by SaschaAdler** [comment]
I've updated the database schemas to add `slug` and `slugAliases` fields to the manifest and collection records.

The code to transfer each slug record should be pretty straightforward:

* Use `type` to determine which database you should be looking up the `noid` in
* Transfer the data to the noid's record as follows:
  * `slug._id` => `obj.slug`
  * `slug.aliases` => `obj.slugAliases`

**Comment by SaschaAdler** [comment]
I gave the new slug views a shot, but I haven't tested them yet.

**Comment by RussellMcOrmond** [comment]
I suspect I should update Smelter and the collection conversion tool first, and then once that is working migrate the current slug database over.

Should we be documenting somewhere that slugs are no longer intended to be globally unique, even if some lookups will fallback to the alternate database?  Slugs are unique only within their document type (manifest, collection).

**Comment by SaschaAdler** [comment]
We're done here, I believe.
