### ISSUE TITLE
The picoswiftstack image has been removed from the Docker Hub

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#391]
I haven't set things up on this laptop in a long time, and it turns out that `picoswiftstack` is gone. I'm not sure what we'd like to do as an alternative.

**Comment by RussellMcOrmond** [comment]
I have not investigated in detail, but https://hub.docker.com/r/openstackswift/saio might be what we are looking for.

https://github.com/openstack/swift/blob/master/docker/dockerhub_description.md
I'm also assuming this is what is built from  https://github.com/openstack/swift/blob/master/Dockerfile


This is based on the instructions for the development VM, which I also haven't had a chance to look into yet:
https://docs.openstack.org/swift/latest/development_saio.html



Alerting @hstgelais-crkn-rcdr , who may want to glance at some of this as well.

**Comment by RussellMcOrmond** [comment]
Sorry, just noticed the note that the other sites are a mirror of https://opendev.org/openstack/swift

But it is useful to know what those who purchased SwiftStack are doing https://github.com/NVIDIA?q=swift
