### ISSUE TITLE
Access Object Storage scheme

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#4]
Re: https://github.com/crkn-rcdr/Access-Platform/blob/master/Policy/Access-Object-Storage-scheme.md

I believe we have some data we want to store in Swift, and some we want in CouchDB.  In order to not lose track, we should probably mention both in this scheme.

Missing from the Swift storage scheme is some data structure for manifests. From METS we have the following beyond the dmdSec (and embedded OCR data, which we will separate):
* top-level label
* array of array of labels,references to canvases (canonicalMaster, canonicalDownload)

I assume /v1/access/metadata is intended to reference a metadata container, and /v1/access/files is intended to reference a files container.

I believe we should focus on reason we would want separate containers.  For instance, if we want a different access or storage policy, or wanted to account for used storage separately, we would need a separate container.  This is also the case if there are ID's in different namespaces.   I'm not certain if this applies to a "files" vs "metadata" separation.

I'm not sure I understand what $file is, which would be a file that wasn't associated with a $collection, $manifest or $canvas.

* Images,  OCR derivatives (XML, PDF) and heritage tags are associated with a $canvas
* multi-page OCR derivative PDFs, or born digital PDFs, are associated with a $manifest
* descriptive metadata is associated with a $collection, $manifest or (later) $canvas.

Are there other files I'm forgetting?

Are the $collection, $manifest, $canvas noids all from the same namespace, and thus could never clash?

Other issues:  Swift is very inefficient in storing a large number of small files.  It might be that the json and xml files we aren't intending to offer direct patron access to download be stored within a zip file, and decompressed as part of processing.

Maybe a different scheme entirely:

* /v1/access/metadata could be $collection.zip , $manifest.zip and $canvas.zip
* /v1/access/files could be $manifest.pdf , $canvas.jpg, $canvas.jp2 , $canvas.tif , $canvas.pdf  ?

All these files would then be stored within the same Swift container (multiple copies, etc), with CouchDB used for faster API access to a processed version of the metadata (to allow views, quick "press" like creation of access and search documents, etc).

**Comment by SaschaAdler** [comment]
> I believe we have some data we want to store in Swift, and some we want in CouchDB. In order to not lose track, we should probably mention both in this scheme.
> 
> Missing from the Swift storage scheme is some data structure for manifests. From METS we have the following beyond the dmdSec (and embedded OCR data, which we will separate):
> 
> * top-level label
> * array of array of labels,references to canvases (canonicalMaster, canonicalDownload)

I didn't include Couch stuff, which is where I expected this information to reside. We should include it in the scheme.

> I assume /v1/access/metadata is intended to reference a metadata container, and /v1/access/files is intended to reference a files container.
> 
> I believe we should focus on reason we would want separate containers. For instance, if we want a different access or storage policy, or wanted to account for used storage separately, we would need a separate container. This is also the case if there are ID's in different namespaces. I'm not certain if this applies to a "files" vs "metadata" separation.
> 
> I'm not sure I understand what $file is, which would be a file that wasn't associated with a $collection, $manifest or $canvas.

I envisioned $file and the files container to be a place for file downloads (PDFs, images, etc.) that are distinct from downloading metadata records. Obviously there's no need to do this. 

> * Images,  OCR derivatives (XML, PDF) and heritage tags are associated with a $canvas
> * multi-page OCR derivative PDFs, or born digital PDFs, are associated with a $manifest
> * descriptive metadata is associated with a $collection, $manifest or (later) $canvas.
> 
> Are there other files I'm forgetting?

That sounds right. I expect we'll be moving Heritage tag info into this scheme at some point, which is as close to "descriptive metadata" for canvases as we get.

> Are the $collection, $manifest, $canvas noids all from the same namespace, and thus could never clash?

See the [noid](https://github.com/crkn-rcdr/noid) service, which doesn't currently mint noids for collections. We can change that, as well, although Natalie and I have chatted about this and we believe collections don't present the same persistence requirements as manifests and canvases; we can use slugs to maintain uniqueness requirements.

> Other issues: Swift is very inefficient in storing a large number of small files. It might be that the json and xml files we aren't intending to offer direct patron access to download be stored within a zip file, and decompressed as part of processing.
> 
> Maybe a different scheme entirely:
> 
> * /v1/access/metadata could be $collection.zip , $manifest.zip and $canvas.zip
> * /v1/access/files could be $manifest.pdf , $canvas.jpg, $canvas.jp2 , $canvas.tif , $canvas.pdf  ?
> 
> All these files would then be stored within the same Swift container (multiple copies, etc), with CouchDB used for faster API access to a processed version of the metadata (to allow views, quick "press" like creation of access and search documents, etc).

I'm fine with archiving and compressing blobs of metadata for things that aren't to be directly accessed by patrons. I wonder about doing this on the canvas level, though; won't we still have a large number of small files as a result? We could group canvas information into manifests, but this runs counter to what I was hoping was the general aim of decoupling canvas information from manifests whenever we can.

**Comment by RussellMcOrmond** [comment]
I interpret the noid service as being globally unique.  While collections don't need globally unique identifiers, they do need locally (to CRKN) unique ones.  Can a slug of a collection be changed like with manifests and canvases?

We should use zip to group files when we can, but we can't get away from there being some small files.  Your interpretation of the aim is the same as mine: that a canvas is decoupled from any specific manifest.

**Comment by SaschaAdler** [comment]
Collection slugs, like manifest and canvas slugs, can be changed. All slugs are required to be locally unique. (Manifests and canvases that persist beyond the point where their slug gets updated to reference a new one no longer can be directly referenced by a slug.)

**Comment by RussellMcOrmond** [comment]
I was thinking more about the requirement of the collection ID needing to be locally unique, separate from the slug also needing to be locally unique.

**Comment by SaschaAdler** [comment]
If we don't need persistent identifiers for collections, the slug can be the identifier.

**Comment by RussellMcOrmond** [comment]
I'm thinking from a database point of view.  If a 'rename' operation exists for a non-persistent identifier, it means copying data from the old to new and deleting the old rather than just changing a field.

**Comment by SaschaAdler** [comment]
If we want to avoid that for slug renames we can just generate whatever identifier we like (and it might as well be a noid, in that case, even if we aren't using it as part of an ARK publicly).

**Comment by SaschaAdler** [comment]
We can generate collection noids now. They'll be prefixed with `s` and then the number of the current NOID database.

**Comment by RussellMcOrmond** [comment]
We don't have all the data I wanted to have to decide if we wanted to put put smaller metadata files (things not images or PDF files) into zip files.  I had hoped to have deleted all the unused directories from "AUTH_crkn/repoanalysis" to determine how much disk space the remaining zip files took.   While I can easily calculate the size of the objects, that isn't the same thing as the storage used as it is the overhead we are trying to determine.

Reason:  The replication between UAB and UTL has started, and running the processing to delete the unused directories is slowing down the replication.  I'll restart that cleanup at a later date.

I believe we know that accessing multiple components of a zip file will be faster for processing (the overhead of setting up an https request once vs multiple times), but that may not be sufficient reasons to justify the increased complexity of managing the zip file.

We'll want to decide on what delimiter we will used.   We'll want to be able to have $noid$delimiter$type be very clean such that using a $noid$delimiter prefix container get request will quickly return all the files related to a $noid .  It only needs to be a character that isn't valid within a noid.

**Comment by RussellMcOrmond** [comment]
I'm back to thinking about this, as I'm needing to start real work on https://trello.com/c/bT063BoP/88-83-develop-the-one-time-series-record-migration-tool

I'll update the documentation to discuss the prefix more specifically.

There are a few domains:

* https://swift.canadiana.ca   - will point to all Swift proxies, to be used when authentication not used (temp URLs, anonymous access allowed).
* https://swift-tor.canadiana.ca - will point to Toronto proxies
* https://swift-uab.canadiana.ca - will point to Edmonton proxies

Containers will be under AUTH_crkn, making the general prefix https://swift.canadiana.ca/v1/AUTH_crkn/

**Comment by SaschaAdler** [comment]
The last thing to do with this is to remove the unused parl.json and EQOD data references. We're storing those in a temporary couch database and will merge them more effectively into the access platform data at a later date.

**Comment by RussellMcOrmond** [comment]
Updated description to point to https://github.com/crkn-rcdr/Access-Platform/blob/master/Policy/Access-Object-Storage-scheme.md

Removed reference todmdPARL.json and dmdHERITAGE.json in  d2562bc7e2121d29dd85d912aeba2df7f647996d

I want to confirm with @SaschaAdler that we can close this issue.

**Comment by SaschaAdler** [comment]
I can confirm.
