### ISSUE TITLE
Hammer2 doesn't clear out old record correctly.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#400]
When a slug is changed, Hammer2 is supposed to look up the NOID to ensure the record at the old transparent ID is removed before the new record as the new transparent ID is created.

This is apparently not happening.  @BeS4  changed the ID for oocihm.lac_reel_t16366 , but https://heritage-demo.canadiana.ca/view/oocihm.lac_reel_t16366/1?r=0&s=1 still exists.

**Comment by RussellMcOrmond** [comment]
http://iris.tor.c7a.ca:5984/_utils/index.html#database/copresentation2/oocihm.lac_reel_t16366 has:

"noid": "69429/m0zc7rn3130s"
 
That ID currently has the slug of "BESoocihm.lac_reel_t16366"
https://access.canadiana.ca/object/69429/m0zc7rn3130s

https://heritage-demo.canadiana.ca/view/BESoocihm.lac_reel_t16366/1?r=0&s=1 also exists.


FYI to @brittnylapierre

**Comment by RussellMcOrmond** [comment]
Apparently this is a TODO in the code that was never worked on, and which also needs to be changed to support slugs being mandatory and the slug changing rather than being removed.


https://github.com/crkn-rcdr/CIHM-Meta/blob/d32e0454bd50fa3ed7fff5b20e0d9d57aac3d947/lib/CIHM/Meta/Hammer2/Process.pm#L162-L175

**Comment by brittnylapierre** [comment]
I fixed the example with the issue that Russell provided for Beth, so you won't see the problem anymore with the manifests above. We'll have to replicate the issue with our own manifest to test a fix.

**Comment by RussellMcOrmond** [comment]
We have a problem in our logic currently, which we will want to decide which way we wish to fix.

The Hammer2 code assumed that the only slugs that would change are those which were already unpublished.  It is unpublishing an existing slug that actually removes it from the cosearch and copresentation databases.

If you change the slug for something published, then the system needs to look up the noid and ensure that the old slug is unpublished as part of publishing the new one.

We either want to enhance the logic in Hammer2, or enhance the logic in the web interface to disallow changing the slug without first unpublishing the old slug - and ensuring that Hammer2 -- AKA: what uses updateInternalmeta{} is finished..

**Comment by RussellMcOrmond** [comment]
Hammer2 currently acts as a bridge between new Access databases which use an Opaque ID as primary key to older databases that use a Transparent ID as the primary key.   If we do this work as a Hammer2 enhancement:

* Add NOID to internalmeta2 documents (currently is only put into attachments, so they do exist in later documents).
* Create _view of noid to be able to look up these IDs.
* Hammer2 would look up and force as unpublished the document in internalmeta2 (primary key is TID), and remove noid, before pushing new information to new TID.  Press would run and remove related documents from cosearch2/copresentation2.

**Comment by RussellMcOrmond** [comment]
Since the last comment I have thought of a different solution, and would like feedback from @SaschaAdler , @brittnylapierre  and @DivyaKrishnan26 .


* Merge logic of Press into Hammer2
  * They needed to be separate in the past because we had tools like https://admin.canadiana.ca/internalmeta which manipulated the data, and we needed to then push the combined changes.  Now the only source for `internalmeta2` data is Hammer2 itself. Along with other benefits, will save disk space as we won't need the `internalmeta2` database any more.
  * Rather than the `order`, `items` and `itemscount` being built from [_view/issues](https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/internalmeta2/design/tdr/views/issues.js) they would be built directly from the Access document (multi-part collection). These fields coming from the multi-part collection also means we don't need to run Hammer2 again when a member is updated (press currently triggers the 'pkey' to process again when a member is updated so that the members/etc of the parent are current)
  * Views now exist for [cosearch2](https://github.com/crkn-rcdr/Access-Platform/tree/main/services/couchdb/cosearch2/design/access/views) and [copresentation2](https://github.com/crkn-rcdr/Access-Platform/tree/main/services/couchdb/copresentation2/design/access/views) to do look-ups by `noid` and `pkey`, making cleanup easy.  When we redesign databases in the future I hope we will have OIDs in any page lookup rather than TIDs, so the changing of a TID doesn't make cleanup more complex and create potential race conditions.
  * Does CAP use `seq` at all? [Cosearch-copresentation](https://crkn.sharepoint.com/:x:/s/platform/Ed9hL3v-q_xMr9XGgMAd9s0BCC5FQbO08tyb7Zlvv3viCw?e=X25SYk) indicates it is put into copresentation for both items and components.



Note: I'm deliberately not talking about `pkey` and `plabel` which are based on the assumption that a manifest can only be a member of a single multi-part collection. Thinking about that is out of scope for this specific project.

**Comment by RussellMcOrmond** [comment]
Additional thought:  To avoid any other document cleanup issues, I would like to add a "parentnoid" field to all type=page documents.  This way there is no confusion between a new or old slug, and no need to be concerned about slugs during cleanup at all.

An `updateInternalmeta` run would:

* Delete documents in `cosearch2` and `copresentation2` where `noid` or `parentnoid` is the current `access` document noid
* Re-create documents if `access` document is marked public.


As part of a final cleanup I would run Hammer2 again on all Access documents, and then remove any documents where the `noid` or `parentnoid` isn't set or doesn't exist in `access` (slug was renamed, and then access document deleted).

**Comment by RussellMcOrmond** [comment]
For clarify of meaning, I've used the field name `manifest_noid`, as this only applies to components built from canvases which are part of a manifest.

https://github.com/crkn-rcdr/solr/commit/8b05e2348061d81146bb15a28bc9c0a5404711f6

Also updated [cosearch-copresentation spreadsheet](https://crkn.sharepoint.com/:x:/r/sites/platform/Shared%20Documents/Projects/Access%20Platform1/cosearch-copresentation.xlsx?d=w7b2f61dfabfe4cfcafd5c680c01df6cd&csf=1&web=1&e=mDmxfQ).

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/CIHM-Meta/commit/93570b08fdea5491fec2be9b6e477d451a17d9f3 adds the field to the existing Hammer2 an press so documents currently being updated will have the field.

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/CIHM-Meta/commit/b7f58e4ecce0bfae6399912d2dd2a886073c2a4a

Updated Hammer2 so there wouldn't be dangling documents in `internalmeta2` when the slug changes.

**Comment by RussellMcOrmond** [comment]
http://gouda.tor.c7a.ca:5984/_utils/index.html#database/internalmeta2/_find

Mango query to find anything missing a noid from the updated Hammer2:

```
{
   "selector": {
      "noid": {
         "$exists": false
      }
   },
   "fields": [
      "_id"
   ]
 }
```

```
bl.test
bl.test1
bl.test10
bl.test11
bl.test12
bl.test5
bl.testd
oocihm.81289b
oocihm.81289c
oocihm.8_00497_2rwm
oocihm.8_00497_3rwm
oocihm.8_06786_14
oocihm.lac_reel_c11431
oocihm.lac_reel_c2352
oocihm.lac_reel_t11989
oocihm.lac_reel_t15691
oop.proc_SOC_1703_1
rwmoocihm.8_01385_2
```

I have tested the update to Hammer2 partly by changing the slug of  https://access.canadiana.ca/object/edit/69429/m0d50ft8jw60 to these different IDs and confirming they disappear when the slug is changed again.
