### ISSUE TITLE
"Click for Help" button

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#402]
I recommend creating a "help.md" file which is what is linked to via the "Click for Help" button on https://access.canadiana.ca/

This could reference the glossary, other documentation, as well as a pointer to different places to provide us feedback ( https://github.com/crkn-rcdr/Access-Platform/issues for the general public or for when questions/answers can be public, but staff suggested to use Email and Slack in other instances).

This would be a page for users of the tool, different than README.md which is more for developers.

See: #376

**Comment by DivyaKrishnan26** [comment]
Closed in https://github.com/crkn-rcdr/Access-Platform/pull/444
