### ISSUE TITLE
Assumptions made about transparent IDs in existing metadata bus

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#403]
This is not part of PASplit, but something we want to think about soon.

There is code in the current metadatabus which makes assumptions about the transparent ID's.

For instance, when Press deletes the older page documents it does so by assuming that the ID's are in the format of  $manifestSlug, a period, and then something else.  If ever there was a slug that had two periods, and the first part matched a different slug, then this pattern would delete all the records for the slug with two periods.

https://github.com/crkn-rcdr/CIHM-Meta/blob/d32e0454bd50fa3ed7fff5b20e0d9d57aac3d947/lib/CIHM/Meta/Press/Process.pm#L375-L387

* Short term
  * We ensure staff know to continue to use the same method for allocating transparent IDs as they did in the past, meaning *exactly one period* in any "multi-part" collection (AKA: series) or manifest.  "unordered" collections aren't pushed into the old metadatabus, so their TIDs won't cause any issues.
  * I don't know if it is worth baking this limitation into the assigning of slugs, or dealing with this in documentation
* Longer term: replace the metadata bus.  This is a medium sized project, depending on which direction we take.
  * I believe we have two broad directions:
    * Upgrade the existing metadatabus to use OIDs rather than TIDs to manage records, avoiding assumptions about how the IDs are formed.
    * Replace the metadatabus (Hammer2, press, solrstream) with new tools that interacts directly with Solr and Presentation documents, using the OIDs to manage records rather than the TIDs (even if TIDs are the primary keys in some databases).  This may require upgrading CAP accordingly.  This is also a good time to split the Solr search cores between document-level search and page-level search.  #340

**Comment by SaschaAdler** [comment]
I think splitting Solr search cores and only using OIDs to reference canvases/pages is a useful first step, regardless of which longer-term direction we choose to go in. CAP can be easily modified to support this, as there are currently no searches that take place simultaneously across series/issues/monographs and pages.

**Comment by RussellMcOrmond** [comment]
I need to evaluate the current state of this, as quite a bit of work has been done on using NOIDs in cosearch/copresentation as part of https://github.com/crkn-rcdr/cihm-metadatabus/issues/23

**Comment by RussellMcOrmond** [comment]
The current metadatabus uses noids when removing old documents from cosearch/copresentation, so this particular issue has been dealt with.

Software which replaces the metadatabus in the future will need to take different identifiers into consideration.
