### ISSUE TITLE
Update editor to handle "pdf" type Access documents

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#407]
Specs cleaned up as part of https://github.com/crkn-rcdr/Access-Platform/commit/2b99d5354ef6be330f14c9289882b95e1ceb851d

There is a new object type="pdf", in addition to type="manifest" and type="collection".

Similar functionality to manifests will be needed as far as publish/unpublish, delete, change slug and change label.

Some design decisions need to be made about whether to offer a PDF viewer within editor to make setting the pageLabels[] array easier.

https://admin.canadiana.ca/couchview/access/tree/pdf?group=1&reduce=true and click on "file" to get a list of ID's that have a born digital PDF.

Later https://admin.canadiana.ca/couchview/access/access/type?group=1&reduce=true will also show the list, but the data hasn't yet been migrated.

**Comment by SaschaAdler** [comment]
I have an idea re: pageLabels (and doing anything more interesting than slug/label editing):

The CAP born-digital experience is far subpar to just downloading the PDF and looking at it directly. Why don't we update CAP to direct users to do that? We can then ignore pageLabels and avoid having to set up anything special.

We could even use the browser's default PDF embed to handle this, although I think a download link would be sufficient.
