### ISSUE TITLE
DMD - On-demand updating

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#420]
User Story: 
As a Metadata Analyst I need to be able to upload and process metadata files quickly so that I can add or update metadata without constantly having to task switch.

- [ ] Design a queue system so that the users don't have to wait for the 10 minute process trigger
- [ ] ...todos

**Comment by RussellMcOrmond** [comment]
https://github.com/crkn-rcdr/CIHM-Meta/tree/main/lib/CIHM/Meta/Dmdtask can easily be made into a service with an HTTP interface to allow a request to immediately start processing a supplied ID.  It could have a maximum number of parallel requests, and indicate in a reply if the request goes beyond the maximum (in which case, wait for queue to complete).
