### ISSUE TITLE
Ability to delete Access objects that have never been published.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#429]
https://access.canadiana.ca/object/69429/g0057cr5n895 is an example of a collection that was created, but never published.  It therefore didn't have any updateInternalmeta{} field to look at to ensure it was unpublished before deleting..

* Uncaught (in promise) TypeError: Cannot read properties of undefined

**Comment by brittnylapierre** [comment]
I just tested my fix quickly by deleting the test collection using the editor on my branch if you're wondering where the collection went before I get to speak with you tomorrow
