### ISSUE TITLE
Add an update to canvas schema for Cantaloupe lookup.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#45]
The bulk Smelter run 'completed', with several errors.  The errors largely related to temporary failures to communicate with Cantaloupe, and the vast majority of time spent during the running of Smelter is the Cantaloupe lookups.

I'm proposing the Cantaloupe lookups be separated from Smelter.  Smelter would create an incomplete canvas record, and a _view against that database would list canvases which had not yet succeeded or failed to communicate with Cantaloupe to fill in any fields we wish to add from Cantaloupe (currently image dimensions).

A separate micro-service would be created to do the canvas lookup.

**Comment by SaschaAdler** [comment]
The update will be added as canvas.master.update, and canvas.master.width and canvas.master.height will no longer be required fields.

**Comment by SaschaAdler** [comment]
Closed by #46.
