### ISSUE TITLE
Access object not showing up on demo site (not sure if bug)

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#459]
Is there a delay when someone presses publish for something to come up of the demo site? https://www-demo.canadiana.ca/view/oocihm.N_00339 is showing not found for this manifest: https://access.canadiana.ca/object/edit/69429/s03f4kk95g5s

Beth noticed: It looks like someone tried to bring it into the access platform on Jan. 10th - it's in the "Warnings and Failures" list in "Import into Access" with the message "Caught" First DIV of METS isn't type=document|issue| , but type=series

Beth has also been trying to add manifests to this collection: https://www-demo.canadiana.ca/view/oocihm.N_00724

But the members list hasn't updated yet on the demo site. 

Is there a delay for membership propagation? I'll note that in the members tab in the editor if so. 

She would like to know how long it should take for an issue to show up online once it's been imported? 5 mins, 10 mins, or longer?

**Comment by RussellMcOrmond** [comment]
One piece at a time:

http://iris.tor.c7a.ca:5984/_utils/index.html#database/access/69429%2Fs03f4kk95g5s

We discussed this elsewhere, which is creating an interface for the `updateInternalmeta` field.  Errors are possible, and having a way to initiate these, view and clear errors would be helpful.

https://access.canadiana.ca/object/edit/69429/m06w9668dv41 isn't published.

**Comment by RussellMcOrmond** [comment]
BTW: "message": "Caught: Missing dmdType\n"

This means that the descriptive metadata hadn't been uploaded before processing was requested.

**Comment by brittnylapierre** [comment]
Thank you!! I let Beth know.

I do think we should add the error to the editor too, I'll add this to proposed then, if it isn't already there, so that we can go through when I should implement that.

"updateInternalmeta": {
    "requestDate": "2022-01-16T15:07:07Z",
    "processDate": "2022-01-16T15:15:18Z",
    "succeeded": false,
    "message": "Caught: Missing dmdType\n"
  }

I was going to ask if I should check for dmdType before publishing but you answered that for me above!

--- 

For the second test, we published the collection and manifest, and are wondering if there is an expected delay for the content to show up? Or maybe the admin code isn't triggering the updates as expected?

Parent Collection:
https://access.canadiana.ca/object/edit/69429/s01j9765bk7h
http://iris.tor.c7a.ca:5984/_utils/index.html#database/access/69429%2Fs01j9765bk7h
https://www-demo.canadiana.ca/view/oocihm.N_00724 (empty)

I try changed the label of the collection to try and see if that would trigger an update, so far the updateInternalmeta object is the same. The updated field was changed to "2022-01-18T20:40:03Z" though.

We have also added a member,

Member Manifest:
https://access.canadiana.ca/object/edit/69429/m06w9668dv41
http://iris.tor.c7a.ca:5984/_utils/index.html#database/access/69429%2Fm06w9668dv41
https://www-demo.canadiana.ca/view/ooocihm.N_00724_19130521 (not found)


I forget if there's a delay between when I press save in the admin tools and when something happens in the demo site, and if there is how long it is it usually? 10 mins - 1hr? I want to add that to the docs if there is~

Alternatively the admin tools could be not triggering the update for the demo site?

**Comment by RussellMcOrmond** [comment]
I think you are answering your own questions :-) 

The updatInternalmeta{} field is what is used by the microservice to know to run.  It then updates the field when it is done its work.  Having that field be displayed will expose to staff everything that is going on (waiting in queue, done and failed, done and success, when these things happened, etc).

https://github.com/crkn-rcdr/Access-Platform/issues/441
https://github.com/crkn-rcdr/Access-Platform/issues/317

**Comment by brittnylapierre** [comment]
Lolol I'm never sure of if what I think is right, is right!

So, when anything changes in the editor, updatInternalmeta.requestDate needs to be updated to now right? This is for any kind of collection or manifest?

This is a bug that I would want to fix right away~

**Comment by RussellMcOrmond** [comment]
You want to call https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/access/design/access/updates/forceUpdate.js whenever anything interesting changes, and you want that reflected in the caches (cosearch, copresentatin) used by CAP.

For ordered collections, this includes updating all members of the collection so that their internal idea of their sequence is correct (as that is no longer part of the descriptive metadata within the member, but data in the collection).

Having a button that just forces the update is a good idea as well, in case an operator wants to just "try again" (there may have been a temporary problem that has since been fixed).
