### ISSUE TITLE
Can't delete item - oocihm.N_00339 possible trouble with metadata

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#469]
Go in "Edit" I see the message "Caught: Missing dmdType"

Steps taken to replace the manifest: 
To replace the existing import of this package, please click here open it in the editor. Then, unpublish the manifest if it is published. Then, press delete to delete the manifest.

Tried to do all that, but it failed to delete it.

**Comment by brittnylapierre** [comment]
@RussellMcOrmond is there any way to see what process failed when the script that updates updateInternalmeta runs?

@BeS4 has a collection that has a no metadata error.

With the logic for deletion, I was checking that the last updateInternalmeta ran successfully. 

This is because it was assumed the last thing done would be unpublishing. This won't always be the case.

Is it safe to allow people to delete delete an item with a failed updateInternalmeta run? 

Thanks!

(Document) https://access.canadiana.ca/object/edit/69429/s03f4kk95g5s

**Comment by brittnylapierre** [comment]
Ah this item is unpublished, but has a failed updateInternalmeta record that is preventing it from being deleted. 

The editor code uses the updateInternalmeta status to check that the processes that happen after something published becomes unpublished finished successfully before allowing deletion.

Does it matter if the last updateInternalmeta process failed? Should I allow deletion in this case? Since updateInternalmeta failures could represent any update to the item that the hammer scripts failed on, not just if the unpublish background processes failed.

Maybe there is a specific error message for the task that unpublishing triggers that I could look for, instead of the succeeded = false?

I think we need the public flag to tell people if their item has been published or not in the UI too, that is how we are doing it currently, but maybe there is another way?

**Comment by RussellMcOrmond** [comment]
It matters if the last updateInternalmeta failed, because we want to make sure that if it was published that we have unpublished it first.  We don't want orphaned cache documents, and want to ensure we have cleared the caches (search and presentation) before we allow the access document to be deleted.

I'm suggesting removing a specific type of failure from the possibilities: if updateInternalmeta was never requested unless dmdType is set, then that Hammer2 error can't happen.  The remaining errors should be ephemeral ones (disk space, network issues, etc) which triggering updateInternalmeta again should resolve.   If we detect other hard-failures (where trying again can't fix the problem), then we can fix the process that would lead to that failure condition.

**Comment by brittnylapierre** [comment]
Ahh okay, this item was imported from preservation and had the dmdType error right away. 

I had been using the package -> manifest language for the importer tool. Is it true that it will be used for collections too? If so I'll update my wording.

This is what Beth sent me this morning: The series record was imported over to Access but it is not showing up online. When I go in "Edit" I see the message "Caught: Missing dmdType".

Then she wanted to delete it to try to re-import it, but then this blocker came because my check is checking for a successful updateInternalmeta process and does not allow for deletion otherwise :o

**Comment by RussellMcOrmond** [comment]
The "makepublic" temporary tool uses the "publish" and "unpublish" update documents in https://github.com/crkn-rcdr/Access-Platform/tree/main/services/couchdb/access/design/access/updates

This might be the source of the problem.  Unpublish will fail with a "Trying to unpublish an object that isn't public", but publish doesn't check for the existence of dmdType before triggering updateInternalmeta{}.

Your wording for "Package -> manifest" is correct.  Collections aren't imported from preservation.

However, "loadseries" and "makepublic" are temporarily being used in the interim to help Beth to get the databases synchronised so we can turn off the old stuff.  I only run "loadseries" when Beth asks me, but "makpublic" is run weekly early Monday morning (you and Beth get a copy of that email).

**Comment by RussellMcOrmond** [comment]
Note to @BeS4 : series records can't be imported from access.  They need to be created in the new tool as multi-part collections.

**Comment by brittnylapierre** [comment]
Note, I changed the slug to: oocihm.N_00339failed to open up the original slug for use
