### ISSUE TITLE
Trigger update for parent collection when member gets deleted from the database 

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#481]
A manifest looks like a slug that was deleted, but a collection it was a member of didn't have its update triggered.

Refactor so that bulkChange is used to update the internalmeta of members of a collection that was edited

**Comment by brittnylapierre** [comment]
Okay! forceUpdate calls updateObject, but so do a few other update functions. Should I move the call  to updateObject out of those other functions, so that lapin just calls forceUpdate when needed for consistency? Or was forceUpdate designed mostly for parents of an object being modified in some way (hence why the editObject calls updateObject, too.) Thanks!

**Comment by RussellMcOrmond** [comment]
You want to be doing what you need to do in as few database calls as possible.  Removing the call to updateObject() seems like creating unnecessary database calls.

The forceUpdate is to force updates on IDs which didn't have one of those things done.

IE:

* unpublish(ID of manifest which is in a multi-part collection)
* forceUpdate(ID of multi-part collection manifest was part of)


Separate:   I suspect services/couchdb/access/design/access/updates/unassignSlug.js should be removed, as slugs are now mandatory.



If you were changing the order of a multi-part collection and need to force the update of all the members of the collection, I suspect you want to do that using your new bulk update functionality and not CouchDB _update documents at all.   The _update functions are only really useful if you have a small number of records you need to change.

**Comment by brittnylapierre** [comment]
Ahh okay so use the bulk api (the bulkChange method I wrote) to edit the updateInternalmeta for many documents at once instead of looping through them and calling force update. That makes sense! I can make that change
