### ISSUE TITLE
OCR format conversion planning

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#5]
Splitting this issue out from #1 

@nataliemacdonald ,

https://www.loc.gov/standards/alto/about.html has some of the background.  It is supported directly by ABBYY Recognition Server.  It is still experimental for Tesseract.

TXTMAP was created by @enouserid , and he had an XSLT script that would convert from the custom files output by PrimeOCR to generate TXTMAP.

We have a number of possibilities:

* Re-OCR all images that have TXTMAP output to generate ALTO using ABBY
* Convert all TXTMAP to ALTO
* Some combination, depending on if positional data is in file. We have some where a .txt from the OCR was wrapped in TXTMAP, and thus no positional information.

This is probably a good time to start to think about this.  If we want to add OCR format to some of the repository analysis, we can do that.  https://github.com/crkn-rcdr/Digital-Preservation/issues/9 

Taking a look at the age of some of the METS records that embed the TXTMAP would also help us in deciding if we want to re-OCR given the current generation ABBYY is going to be far superior to the quite-old PrimeOCR output.

**Comment by RussellMcOrmond** [comment]
Next step in discussion:  Who should design the crosswalk?  Is XSLT something that @nataliemacdonald or another member of the metadata team knows, or does this fall to a platform team developer to implement?

**Comment by nataliemacdonald** [comment]
I'm probably not the best person to do the entire task. I do not have any experience working with OCR metadata in this way. I am more than happy to be part of the process so I can learn, though.
