### ISSUE TITLE
DMD Task Table: When there is a big list it would be nice to have a filter to hide success,  ID lookups that couldn't be found, items where stored was blank or false.

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#506]
Would using Red (Fail), Yellow (no checkbox) and Green (Success) be easier to find the exceptions?  Pages would be smaller as the extra text line wouldn't be needed.

Sometimes one or two items in a task fail. Should there be a filter to show them?

Do staff care who did the upload? Is filtering by staff member important?

**Comment by RussellMcOrmond** [comment]
I'd like to ask about "Searching dmd tasks by filename on the listing page".

Why would there be so many tasks that it wouldn't be trivial for staff to find the one they wanted?

Limiting by staff person would filter out other people's tasks tasks -- and once someone did that, why would there ever be more than one or two left?

There are currently several hundred tasks just lying around as the trashcan button was only recently created.
