### ISSUE TITLE
DMD task: character encoding in "Preview Metadata"

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#509]
https://access.canadiana.ca/dmd/f296cdd98ef39a425878357abab4dddd provides an example.

In the XML the accented characters aren't displayed correctly, but in the JSON tab they are.

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond I'm not sure how to fix this off the top of my head - http://iris.tor.c7a.ca:5984/dmdtask/e80b853dbc1e044004992bfd9729bbab/dmd.json shows the messed up accent text. Is there a method I should call on the strings to replace the weird accent character codes with the correct ones?  (something that would correct: <subfield code="a">EÌducation</subfield>)

Thanks!

**Comment by RussellMcOrmond** [comment]
This is outside my area of expertise.

While there are HTML entities encoding, it shouldn't be required for regular text.  I note the template for the pages has `<meta charset="utf-8" />` , but it might be that the pop-ups need to be separately declared.

https://www.w3.org/International/questions/qa-html-encoding-declarations
https://www.w3.org/TR/html401/sgml/entities.html

**Comment by RussellMcOrmond** [comment]
This was a bug in the microservice, not a problem with the web interface.  https://github.com/crkn-rcdr/cihm-metadatabus/issues/29

Sorry for that confusion.
