### ISSUE TITLE
canvas takedowns

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#51]
There's no reason why staff shouldn't be able to access images that have been taken down, or revert takedowns, which would be difficult if the database spec did not allow for the original master content to stick around.

**Comment by SaschaAdler** [comment]
I'm having a think about this and a related issue, and so I'm generalizing this issue as a place for thoughts about takedowns.

The IIIF Presentation API has a descriptive property called [`behavior`](https://iiif.io/api/presentation/3.0/#behavior) which when applied to a manifest describes how the manifest's canvases should be laid out (when the manifest doesn't describe an audio/video resource, anyway). If `behavior` is set to `paged` the manifest will be displayed as if it were a document with pages, with the first page as the first recto (i.e. the front cover) and then two canvases side-by-side at a time. I think being able to display our paged content in this manner is a huge boon, both because it will make our own viewing experience better when we use a IIIF viewer, but also when other people consume our IIIF resources for their own viewing. I'll be looking to add some property akin to the IIIF `behavior` property to our database schemas.

When we take down a canvas in a volume-like manifest for copyright or privacy reasons, we shouldn't disturb the recto-verso nature of the manifest's canvas order. I propose that we create some generic "takedown" canvases to insert in our publicly-available IIIF derivatives as a replacement for the canvases that have been taken down. I'm sure our communications team will be excited to apply the best of our branding to the images we'll use in this situation. :grinning: The canvases database can continue to point to the taken-down image, in case we decide to undo our takedown decision.

We could also create a canvas that shows something like "this page intentionally left blank" for canvases we insert in order to fix `paged` ordering problems, although if you set a canvas' `behavior` to `facing-pages` for anything that either corresponds to two facing pages at once, or something that isn't part of the book (like a technical data sheet, if we care about keeping those), the canvas will be ignored in the `paged` ordering.

**Comment by RussellMcOrmond** [comment]
I am a fan of the idea of having a few jpeg files we include within https://github.com/crkn-rcdr/cihm-cantaloupe that are bilingual pages that we present when the policy within a canvas document has specific flags.  A canvas document still exists, and may or may not have an image within Swift associated with that canvas, but that one of the pre-generated images is offered when that canvas is requested.


There is a set of "this page left intentionally blank" placeholders which the production team has been copying into AIPs.  My hope is that the new access platform can make that practise in the preservation platform go away.

Longer term having a way for staff to indicate that a given canvas is one of these unnecessarily copied images would be great.  I can provide links to examples if that is helpful, as that was part of what I found with the repository analysis work. https://github.com/crkn-rcdr/Digital-Preservation/tree/master/RepositoryAnalysis

**Comment by SaschaAdler** [comment]
One note based on the rights pilot project is that we're definitely going to need to add Traditional Knowledge as a reason to take down a canvas, and we might also need to add "other". I've asked whether we need to share anything more specific than these categories with our users (and thus keep track of the more specific rationale along with the category) but I'm not sure about that yet.
