### ISSUE TITLE
Update cache: button for individual, but also add to bulk tools.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#519]
This relates to an email from @BeS4 where some IDs needed to have caches regenerated.  The process at the moment is to unpublish and then publish the manifest.

Ideal would be if a "generate cache" option existed, so that the date of when the manifest/collection was published is retained.

A bulk tool that allowed staff to past a list of IDs (slugs and/or noids) to initiate processing would also be very helpful.

----

Currently the field is: `updateInternalmeta: ProcessUpdate.optional(),`

I hope in the future we will rename to something more generic like: `updateCache: ProcessUpdate.optional(),`

The concept of the `internalmeta` database will hopefully go away soon https://github.com/crkn-rcdr/cihm-metadatabus/issues/23

**Comment by RussellMcOrmond** [comment]
@brittnylapierre and I may want to discuss this in more detail.

The current "Press" system will initiate the cache update for a multi-part collection if one of its members are updated.  This was to ensure that the membership was properly updated.

This might need to be reversed with the updated system -- that all member caches need to be regenerated when an ordered collection is, given the members each have the parent label within it (and what if the label was updated).


It might be best for cache generation to be under the control of the Web interface (the client and server of https://github.com/crkn-rcdr/Access-Platform/tree/main/services/admin ) rather than the metadatabus trying to second-guess this.

In the short term, allowing staff to have an easy way to do individual and bulk cache generation would be a great start.  We can document scenarios where regenerating the caches are required, and worry about automating later.

**Comment by RussellMcOrmond** [comment]
This issue is related to https://github.com/crkn-rcdr/cihm-metadatabus/issues/23

If a member of a collection is published first, and later it is added to a collection, the caches of the members aren't updated to reflect the fact that they are now in that collection.

Example:  https://access.canadiana.ca/object/edit/69429/m00000004m5b

```
russell@russell-XPS-13-7390:~$ curl -s http://jarlsberg.tor.c7a.ca:5984/internalmeta2/oocihm.N_00726_18800204 | json_pp
{
   "attachInfo" : {
      "hammer.json" : {
         "uploadDate" : "2022-08-31T15:32:37Z"
      }
   },
   "updated" : "2022-08-31T15:50:05Z",
   "_attachments" : {
      "hammer.json" : {
         "stub" : true,
         "revpos" : 2,
         "digest" : "md5-zGYC5UV9gjokHJD8p5fuYQ==",
         "length" : 1225,
         "content_type" : "application/json"
      }
   },
   "created" : "2022-08-31T15:32:37Z",
   "pubmin" : "1880-01-01T00:00:00.000Z",
   "press" : {
      "message" : "",
      "status" : 1,
      "date" : "2022-08-31T15:50:05Z"
   },
   "label" : "Feb. 4, 1880",
   "approved" : "2022-08-31T15:32:37Z",
   "sub-type" : "document",
   "noid" : "69429/m00000004m5b",
   "collections" : [],
   "parent" : "oocihm.N_00726",
   "_id" : "oocihm.N_00726_18800204",
   "type" : "aip",
   "seq" : "1",
   "_rev" : "4-101da7bfc7e603fbbf0cce1a8be05b2c",
   "collectionDate" : "2022-08-31T15:32:37Z"
}
```

**Comment by RussellMcOrmond** [comment]
The single update on the editor page is mentioned in #440

**Comment by brittnylapierre** [comment]
@BeS4 @JLoitzenbauer-CRKN Hey! I am pushing the changes you tested using the user testing software today. 

Please let me know here or on Slack if you run into trouble.
