### ISSUE TITLE
Newly added or removed members cache generation

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#536]
Call force update to added or removed members of unordered collections

Remember to only force an update on members affected by the change, not all members!

**Comment by brittnylapierre** [comment]
@RussellMcOrmond Just to be sure - this causes the items to not be published sometimes right? That's the bug that John experiences fairly frequently.

**Comment by brittnylapierre** [comment]
@RussellMcOrmond Just to be sure - this causes the items to not be published sometimes right? That's the bug that John experiences fairly frequently.

**Comment by RussellMcOrmond** [comment]
It doesn't relate to whether it is "published" or not, but whether the Solr index and presentation documents will list all the collections it is a member of.   A cache is generated at the moment it is "published", and if it is added to a collection after, the fact it is in the collection isn't indicated.


It is an order-of-operations thing.  If collection maintenance happened first and then things were published, nobody would have noticed the issue.  But we should support something being marked to be published, and then collection management happening after.

**Comment by RussellMcOrmond** [comment]
This ticket is related to #519 , #440

**Comment by brittnylapierre** [comment]
Oh okay - to John and BEth it appears as though publishing didn't occur however the true issue is that the member cache isn't being updated so the item isn't visible through it's parent collection online?

**Comment by RussellMcOrmond** [comment]
CAP showing an item on a given portal requires it is a member of a portal-specific collection.  So to them not being in a collection would appear similar to "not published".

**Comment by brittnylapierre** [comment]
Sounds good that was the source of my confusion then - different vantage points on the issue

**Comment by RussellMcOrmond** [comment]
I hope as part of https://github.com/crkn-rcdr/Access-Platform/issues/521 we will do something smarter with this.

a) Look up the slug or noid.
b) If the document is in the current portal, show it.
c) If the document has a collection list representing a single portal, then redirect to the correct portal.
d) if none of the above, then display a page indicating that the document exists, and what portals it is available on.  Display a special note if no portal offers the document.

The current "404" page is the same whether the ID doesn't exist, or it exists but just not in the right collections.
