### ISSUE TITLE
Install Test version of FOLIO on a CRKN server.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#552]
https://lotus.docs.folio.org/docs/getting-started/installation/

A [Sharepoint document](https://crkn.sharepoint.com/:w:/r/sites/platform/Shared%20Documents/Planning/Access%20Platform/Architecture%20Planning/Research/FOLIO/FOLIO%20Research.docx?d=wd6b6ac708f904b958522abad735b93dd&csf=1&web=1&e=aTAGKO) is being used to discuss overall project.

**Comment by RussellMcOrmond** [comment]
http://oma.ott.c7a.ca:3000/ is where the login will be.

IP address in DNS requires staff to be logged into the Fortinet VPN.

```
[09:50] root@eclipse ~# host oma.ott.c7a.ca
oma.ott.c7a.ca has address 10.200.1.35
```

For those of us that connect to gateway-ott, there is a different IP address to put into /etc/hosts

`10.202.250.42 oma.ott.c7a.ca`


Instructions to replace "localhost" for contacting OKAOPI (required for login) doesn't work with recent snapshots.  I will have to ask about those details.
https://github.com/folio-org/folio-ansible/blob/master/doc/index.md#replace-localhost-by-hostname-on-the-demo-box


Current Vagrantfile.  This will be changing as testing goes forward.

```
Vagrant.configure("2") do |config|
  config.vm.box = "folio/release-core"
  config.vm.network "forwarded_port", guest: 9130, host: 9130
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 65536
    vb.cpus = 8
  end

  config.vm.provision "shell", env: {
    "OKAPI" => "http://oma.ott.c7a.ca:9130"
  }, inline: <<-SHELL
    set -e
    rm -rf /etc/folio/stripes/output
    /etc/folio/stripes/build-run
    docker restart okapi
  SHELL
end
```

This is an old version, but the instructions to set the API URL was close enough to be able to log in:
http://oma.ott.c7a.ca:3000/settings/about

https://dev.folio.org/tutorials/folio-vm/01-create-workspace/

Modifying 
> Use the local web browser to login to the user interface at http://oma.ott.c7a.ca:3000
> The default administrative user is diku_admin/admin
> 
> Inspect the Settings page to find the version of Okapi, and the installed modules:
> http://oma.ott.c7a.ca:3000/settings/about


Currently shows: stripes-core 7.2.0
https://github.com/folio-org/stripes-core/releases/tag/v7.2.0  -- is from Jun 9, 2021.

**Comment by RussellMcOrmond** [comment]
Question posted, awaiting some feedback rather than fiddling with software I don't understand yet :-) 

https://discuss.folio.org/t/new-method-to-replace-localhost-by-hostname-on-the-demo-box-ansible/3404

**Comment by RussellMcOrmond** [comment]
Awaiting feedback from Folio comunity.

In the interim, the old version is available via http://oma.ott.c7a.ca:3000 for @brittnylapierre and @nataliemacdonald to look at. This is only for playing around. Please post feedback here, and I will coordinate future upgrades/etc with the two of you.

This URL is only available while connected to the CRKN VPN, and the default administrator password has been kept.


From https://dev.folio.org/tutorials/folio-vm/01-create-workspace/
"The default administrative user is diku_admin/admin"



For Britney,


If you are connected using OpenVPN via gateway-tor, you don't need to also connect to the Fortinet VPN to access Folio or Archivematica.   You can just put the following in your /etc/hosts:

```
russell@russell-XPS-13-7390:~$ grep oma.ott /etc/hosts
10.202.250.42 oma.ott.c7a.ca
russell@russell-XPS-13-7390:~$ host archivematica-test.c7a.ca
archivematica-test.c7a.ca is an alias for oma.ott.c7a.ca.
oma.ott.c7a.ca has address 10.202.250.42
russell@russell-XPS-13-7390:~$ 
```

**Comment by brittnylapierre** [comment]
Hey Russell! This instance is working for me. 

James said we should look into only keeping the modules we want to use in our test instance. 

To add/keep only the modules and plugins we want, I think this would be the install instructions:

1. Clone the platform repo: https://github.com/crkn-rcdr/folio-platform-custom  (I made a fork of platform-complete and tried to edit it to only contain things we are interested in. There may be errors because of this that need to be fixes as you go.)

2. Follow these instructions to get it running locally. Instead of platform-complete use the above repo (fixes might be necessary!!) https://lotus.docs.folio.org/docs/getting-started/installation/singleserverfreshinstall/  

3. Package it up with vagrant (I think?) https://www.engineyard.com/blog/building-a-vagrant-box-from-start-to-finish/  

4. Deploy the vagrant to the server (I think?)

Thanks!

**Comment by RussellMcOrmond** [comment]
* https://app.vagrantup.com/folio/boxes/release
  * Lists R2-2022 release
* https://github.com/folio-org/folio-ansible/blob/r2-2022-release/doc/index.md
  * Has documentation on [replacing localhost by hostname on the demo box](https://github.com/folio-org/folio-ansible/blob/r2-2022-release/doc/index.md#replace-localhost-by-hostname-on-the-demo-box) that is outdated.


This is the piece of the puzzle we need to figure out before we can move to the new version and try it out.

There is documents on that release page for [running modules on your host system](https://github.com/folio-org/folio-ansible/blob/r2-2022-release/doc/index.md#running-backend-modules-on-your-host-system)
