### ISSUE TITLE
Missing error reporting

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#559]
https://access.canadiana.ca/dmd/12c3c1c4458c7475a2dc8be6ec8cc18b
https://access.canadiana.ca/dmd/12c3c1c4458c7475a2dc8be6ec8ce032
https://access.canadiana.ca/dmd/12c3c1c4458c7475a2dc8be6ec8cf847

**Comment by RussellMcOrmond** [comment]
One way to generate an error staff should be able to see is to create a csv file with incorrect columns:

* "dc: description" (a space)
* "dc:orNotDC"  (a serious question).
