### ISSUE TITLE
Collection Data: Tool to find and remove redundant collection references/links

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#567]
IIIF collections are a graph, but we don't visualise this or provide hints in the existing (quick and dirty) collection editor.  This has caused many instances where a manifest is put into a collection (such as an ordered collection) as well as adding the manifest to collections which the first collection is also a member of.

The idea is to author a tool which examines collections and manifests, and tries to remove those redundant links.

Including a screenshot of an example: 

* **oocihm.N_00339_19031023** is a manifest, and it is a member of **oocihm.N_00339** (Victoria Times)
* **oocihm.N_00339** is a member of **news**
* **news** is a member if **serials**
* **serials** is a member of **online**

That means that having direct links to "serials", "online" and "news" is redundant.  In the future we will want staff to manage this graph directly, but we currently have bad data in the database to clean up.

![Screenshot from 2022-12-08 19-39-18](https://user-images.githubusercontent.com/2487341/206601360-9b18abae-fc65-4358-841c-ca65f29c7675.png)

**Comment by RussellMcOrmond** [comment]
Note: "redundant" is true, but doesn't tell the whole story.

These links mean the membership lists are huge, and is causing major database performance issues.

It will also be a problem for any visualisation for Patrons in the future:

* https://github.com/crkn-rcdr/cap/issues/139
* https://github.com/crkn-rcdr/cap/issues/138


Like some of our descriptive metadata work, collection cleanup is required longer-term.

**Comment by jmacgreg** [comment]
Thanks Russell - this is very clear to me. I'll follow up as mentioned with others.

**Comment by RussellMcOrmond** [comment]
I have started to run the tool.

If you look at "sve" which previously had 4785 members, it now has 4 (the 4 different newspapers, which have all the issues within them).

https://access.canadiana.ca/object/edit/69429/s0zp3vt1hv4t

**Comment by RussellMcOrmond** [comment]
Processed over the winter break.

```
russell@eclipse:/media/crkn-nas-wip/_ACCESS_collections/20230103$ wc -l * | grep -v total | sort -g | tail -20
   1670 oocihm.N_00333.txt
   1743 oocihm.8_06619.txt
   1979 oocihm.N_00193.txt
   1989 oocihm.8_04695.txt
   2012 oocihm.8_06569.txt
   2015 per.txt
   2462 oocihm.8_06663.txt
   2512 oocihm.N_00718.txt
   2930 oocihm.N_00385.txt
   3120 oocihm.8_06526.txt
   3653 annuals.txt
   4839 oocihm.N_00208.txt
   4938 oocihm.N_00358.txt
   5044 parl.txt
   7342 numeris.txt
   8194 govpubs.txt
  12317 oocihm.N_00367.txt
  21732 maps.txt
  28019 dfait.txt
  86160 monog.txt
russell@eclipse:/media/crkn-nas-wip/_ACCESS_collections/20230103$ 
```
