### ISSUE TITLE
OCR data: manifests where an OCR PDF is larger than 5G (Limit of non-segmented files on Swift)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#586]
Swift makes use of an additional protocol feature ( [Large Object Support](https://docs.openstack.org/swift/latest/overview_large_objects.html) )when files are larger than 5G.  We have not set that up for multi-page PDF files, and believe we should have a policy discussion before we add the feature as those files may be too large.

**Comment by RussellMcOrmond** [comment]
Current lost of slugs for manifests which would have larger multi-page OCR PDFs.


```
tdr@00c79eb8bfe4:~$ access-ocrpdfstatus-toobig
Found 25 matches
oocihm.N_00009_189701
oocihm.N_00097_191704
oocihm.N_00296_191101
oocihm.N_00296_191107
oocihm.N_00296_191201
oocihm.N_00296_191207
oocihm.N_00296_191301
oocihm.N_00296_191307
oocihm.N_00296_191401
oocihm.N_00296_191407
oocihm.N_00296_191501
oocihm.N_00296_191507
oocihm.N_00296_191601
oocihm.N_00310_189809
oocihm.N_00310_190209
oocihm.N_00316_191701
oocihm.N_00316_191707
oocihm.N_00316_191801
oocihm.N_00316_191901
oocihm.N_00319_189707
oocihm.N_00319_189909
oocihm.N_00319_190008
oocihm.N_00531_185803
oocihm.N_00531_186408
oocihm.N_00531_187104

tdr@00c79eb8bfe4:~$ 
```
We are still generating multi-page OCR PDF files for Heritage reels, so that list may grow.

It might be the policy will be to split up those manifests rather than keep them this large.

@jjfriedman @jmacgreg @JLoitzenbauer-CRKN

**Comment by RussellMcOrmond** [comment]
@brittnylapierre should be part of this conversation.

As we migrate from the old CAP data model (monographs, series, issues of series), we can hopefully harness the data model IIIF offers.

For example:  Having the document record for a reel be a "multi-part" collection, and ranges of images be individual manifests.  The navigation between different types of collections should be improved to make this all more clear.

See: https://github.com/crkn-rcdr/cap/issues/138 (Labels for "issues" of series, breadcrumb display.)

**Comment by brittnylapierre** [comment]
Definitely to the above - I believe that is the correct way to go forward with reels

**Comment by jjfriedman** [comment]
I'm going to need to understand this better in order to be able to weigh in on the policy discussion referred to above.
