### ISSUE TITLE
Load Metadata:  Options between (a) use label from Metadata file (b) keep existing label

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#594]
I can see a number of situations when staff would want to load new metadata, but not change the label which they already have set the way they want.

The tool should have a way to allow that, and indicate that this has been done to the back-end tool. 

https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/dmd/Task.ts

* A new boolean `shouldSetLabel` could be added to `ItemProcessRecord`?
* existing optional `label` field being undefined could indicate to not set label?

`shouldStore` being true would still mean metadata would be stored, but the Label would have separate logic.

**Comment by brittnylapierre** [comment]
Closing b/c we are going to implement [Edit in Access: Bulk label/description set#599](https://github.com/crkn-rcdr/Access-Platform/issues/599)
