### ISSUE TITLE
Smelter minimum viable operation

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#6]
Discussion towards documenting MVO

**Comment by RussellMcOrmond** [comment]
Hammer currently reads METS records, loads OCR data if external, crosswalks descriptive metadata, and stores results in CouchDB (some as part of document, most as a hammer.json attachment).

We will want to decide how much of the current structure of a hammer.json file gets kept for how we store data for manifests and canvases.


* Operations left in simplified Hammer
   * XSLT/etc to transform dmd XML to current CMR'ish hammer.json file
   * filter out positional data from OCR XML for "tx" field in hammer.json
   * store 'merged' document in current hammer.json format used by press to create search and presentation documents.  Alternatively the micro-service doing the XML -> json and data transformation could store in documents which Press would be enhanced to read from.


* Operations in Smelter
   * read METS records
   * Generate manifest noid for structmap (only 1 for "physical" ever existed)
   * Generate canvas noid for each member DIV in the structmap
   * Use IIIF image server to determine dimensions of master.
   * store separated dmdSec XML
   * store separated OCR XML  (See #5 as we may transform TXTMAP)
   * store structure for manifest, including array of noid references to canvases
   * store structure for each canvas (label, master, master mime type, download, download mime type, etc).
   * (big question - when do we do this) store copy of master images and downloads?


Much of the logic is currently in https://github.com/crkn-rcdr/CIHM-METS-parse , with some in https://github.com/crkn-rcdr/CIHM-Meta/blob/master/lib/CIHM/Meta/Hammer/Process.pm

**Comment by RussellMcOrmond** [comment]
I've added @SaschaAdler to this to get some comments.  I'll edit the first comment with whatever updates we come up with, and then we can move into the next stage of planning.



Related to when we make the copy of master images and downloads....

Until we have the additional Swift servers in operation (2 new in Toronto, and then the 4 for preservation converted from current ZFS), we don't have the disk space to have a second copy of each image and PDF.  We will need to coordinate this part of the process with systems work.

**Comment by SaschaAdler** [comment]
I can't immediately think of anything to add to the list. As to the big question, I think we can have Smelter copy over a link to the current preservation copy of the image/download in question until we have the requisite space available to have multiple copies.

I'm a big fan of using this as the time to transform TXTMAP into ALTO.

I assume a Smelter MVP only needs to be able to do a full create/overwrite of the access objects corresponding to a Preservation AIP, and we don't yet have to concern ourselves with things like "add this set of images to an existing manifest" or "only copy metadata".

**Comment by RussellMcOrmond** [comment]
(I know it's the weekend, but I read your comment...).

There might be some value in thinking more about the create/overwrite/append/partial concept.  If the manifest editor allows easy "copy metadata from" and "append all images from", then Smelter can be kept pretty simple:

* If slug doesn't exist, generate the new manifests and associated canvasses.
* If the slug already exists, treat that as an error requiring the operator to choose a unique slug.  Alternatively it can do one of those _01 things to generate a unique ID before moving forward.

I suspect you already intend to ensure slugs are unique within the UI, so the slug being a duplicate might only be a race condition.  We could decide to do something smarter with that: create blank manifest with slug set, and pass noid into dipstaging rather than Smelter generating that noid...


In the future we might want to integrate the ATOM publishing protocol crkn-rcdr/Digital-Preservation#8 , and it doesn't have as many options available.  Being able to duplicate the functionality that you were thinking of within the manifest editor will make that possible future integration easier.

**Comment by RussellMcOrmond** [comment]
We need to come up with an answer to the policy question within the previous comment: Do we need to support AIP updates.

It is simplest if we can think of Smelter running as a one-time event for any given AIP, and that all the activities that would previously have been done in a SIP or metadata update would be done directly within access platform management tools.

I'm wondering from @enouserid how we want to approach this question with other parts of CRKN?  Is this something we have to invite feedback from anyone else, or decide within CRKN?

**Comment by RussellMcOrmond** [comment]
In Today's planning meeting we decided:

* We won't support AIP updates, but treat Smelter as a one-time operation.  While we should record the manifest date as of the Smelter run, we won't support doing a second run if the manifest date changes.
* Smelter won't support overwrite/append/partial concepts.  If a slug already exists that will be treated as an error.  All management of manifests (adding/removing/reordering canvasses, updating descriptive metadata, updating labels) will happen within staff web tools.  Suggestion is to have a "copy metadata from" to copy between manifests, and "append canvasses from" (all, and/or range?) to allow one manifest to be a source of data for a different manifest.
