### ISSUE TITLE
Import into Access: Packages Never Imported

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#604]
https://access.canadiana.ca/smelter/neversmelted/1/10/all

This is based on https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/dipstaging/design/access/views/neverSmelted.js

This database is a work-queue, and it is normal for records to be cleaned out and then repopulated from the repository. The existence of values in doc.smelt only have meaning when an AIP is in the queue and for temporarily reporting errors/etc. The non-existence of that field doesn't have any defined meaning at all (other than it not being in the current work queue).

The `canvas` database (hopefully to be renamed to `IIIFimage` or similar), knows what images from AIPs have been imported, and if there is a desire to check on such things then that is the database to look at.

In the interim, it may be useful to inform Heritage Services to not attach meaning to that tab, or to remove that tab entirely.

**Comment by RussellMcOrmond** [comment]
Related: https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/dipstaging/design/access/views/newDip.js

There was a short period when these tools were first developed when the concept of a "SIP update" in the packaging system still existed.  This was a view used to help highlight these for staff during the transition.

Since that time, the only updates that can happen after an AIP is created (with a new SIP) is a metadata update. Metadata in Preservation shouldn't be loaded into Access  https://github.com/crkn-rcdr/cihm-metadatabus/issues/70 (that was done temporarily during the transition in spring 2022) , so these types of updates have no relevance to the Access platform.

There are many assumptions being made in that view about the meaning of some values that isn't strictly true, including the meaning of doc.smelt and dates within it.

**Comment by jmacgreg** [comment]
Will need some discussion at our dev meeting tomorrow.

**Comment by RussellMcOrmond** [comment]
Also "Packages with Recent Activity", which also doesn't make sense in this context.  There are other databases for that if it was desired...
