### ISSUE TITLE
OCR data: manifests with broken PDFs ("path" reference).

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#607]
After running #605, there are a series of manifests where no replacement PDF could be generated.

* Some are "Not all canvases have OCR data" https://access.canadiana.ca/object/edit/69429/m0pz51g0ns4q
* Some have larger issues with the PDF files https://access.canadiana.ca/object/edit/69429/m0pr7mp4vz2r

These are manifests where OCR should be re-done, as these older (broken) PDF files won't be available at all as we continue the process of splitting preservation from access, and moving toward Archivematica.

**Comment by RussellMcOrmond** [comment]
[access-ocrpdf-pdfpath-list.txt](https://github.com/crkn-rcdr/Access-Platform/files/11257187/access-ocrpdf-pdfpath-list.txt)

8116 /home/tdr/datadl/access-ocrpdf-pdfpath-list.txt

**Comment by JLoitzenbauer-CRKN** [comment]
I've started the export of a few batches today.  The first batch, 36799 canvases, will go in for OCR processing tomorrow.

**Comment by RussellMcOrmond** [comment]
@JLoitzenbauer-CRKN ,

Can you ask within Heritage Services a policy question.

These broken PDF's are currently able to be downloaded from the websites offered by CAP.  Since you currently have a list, and are creating good PDF replacements, I would like to disable the reference to the broken PDF. I'd like to get some feedback from HS about whether they agree to this, or if we have to wait until the broken PDFs have been replaced with good PDFs.


Having all Access services (like CAP) no longer referencing Preservation storage is part of the cleanup of the Preservation-Access Split, which is a prerequisite to our being able to complete the Archivematica Adoption project in the future.


Cc: @BeS4 , @jmacgreg

**Comment by RussellMcOrmond** [comment]
@JLoitzenbauer-CRKN ,

Let me know if you ever want an update to that file listing of slugs.

The databases indicate only 7968 now, so can see the progress.

**Comment by JLoitzenbauer-CRKN** [comment]
I'm good for now.  Slowly plugging away.  The OCR is going pretty fast.  New ABBYY is definitely more efficient.

**Comment by jjfriedman** [comment]
@JLoitzenbauer-CRKN When you get a chance, can you provide an update on the replacement PDFs?

**Comment by JLoitzenbauer-CRKN** [comment]
I've exported 1104 out of 8100 manifests so far.  They have all been OCR'd. 

Imported:
CAP_PDF_error_1
36799 canvases
CAP_PDF_2
5744 canvases

Waiting on Import:

CAP_PDF_error_3
78680 canvases
CAP_PDF_error_4
61086 canvases

The main bottle neck is LOAD OCR import and export times.  Also I've been doing GAC and Annuals at the same time which have higher priority.

**Comment by JLoitzenbauer-CRKN** [comment]
I've exported and OCR'd another 140k canvases.  Just waiting on the import for Batch 3 and 4 to finish then I will import that batch.
