### ISSUE TITLE
Slug definitions and lookups with prefixes

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#62]
In our database schemas slugs are defined simply as arbitrary strings. I think we should ensure that they're limited to a subset of characters that won't cause problems with URL encoding. I propose `[a-zA-Z0-9._-]` but we could add others if we think it's useful.

Related to this issue is what we'd like to do long-term about slug lookup "prefixes". I suspect that for batch lookup tools, staff will want to continue selecting a prefix for each lookup, and having it prepended to every string they provide. I'm not sure of the best way to suggest that while this is still possible, slugs don't need to live in the same sort of depositor "domain" that AIP ids do in our legacy preservation platform. We'll also want to support prefixes that aren't depositor names, like `oocihm.lac_reel_` or even `oocihm.9_`. Should we maintain a list of these prefixes and have users select from a drop-down, or should we just let them type in whatever and hope that they didn't make a typo? Since we're only talking about lookups here I doubt the latter is dangerous, but it could be annoying.

**Comment by RussellMcOrmond** [comment]
I like your suggested character filter.  If there is something that is desired that doesn't match the filter we can discuss it then. We may want to author tools such that URL encoding is supported, in case we have a need to expand in the future.  I will be surprised if a request isn't eventually made to support accents for French slugs.


For the lookup prefixes, we have some options.

For instance, we currently have staff use a pull-down of the prefixes we have configured.  If we wanted to get smart about things we could have that happen automatically.  We could write a server-side function for sapindale which would take an array of slugs, and return an array of slugs.   It would take that array and do database lookups without prefix, and if it gets any missing would loop through the possible prefixes to try to find a match.  (Each request to CouchDB would be a keys array that would be hopefully getting smaller with each subset that hasn't yet been found).

We would then build an array of prefixes that is based on what the most common prefixes people want are.  The fact that many popular prefixes happen to have been depositors in the preservation platform is an interesting coincidence :-)

**Comment by SaschaAdler** [comment]
Modern versions of Perl and JavaScript appear to handle [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes), which we can use instead of the ASCII letters in our filter. A filter like `/^[\p{L}0-9_\-.]+$/u` would match every Unicode letter, along with 0-9, underscore, hyphen, and full stop. We could use Unicode properties for numbers and punctuation also, although at least for the full stop we'll want to avoid using its category of "Punctuation, other" as it contains scary things.

I don't love the idea of automating the prefix search for the set of keys, partially because I think it would be beneficial for people to have to reckon with the full slug at all times, and also because I'm not sure how to decide between the hypothetical `oocihm.thing` and `oop.thing`, for example, other than picking one to look up before the other. It seems like we'd be adding semantics to prefixes and we're trying to remove semantics from prefixes.

Maybe we go with a set of known prefixes and then also allow the user to specify one we haven't heard about yet.

**Comment by DivyaKrishnan26** [comment]
While prefixing is discussed here, i notice that there are slugs with no designated prefixes(eg: online, serials).  I think about a case where the user decides to select in ("oocihm") as their prefix and have a list of slugs to lookup and also  search the "online" or "serial" which is going to result in "not found" but the slug actually being present. I am assuming the prefix selection is something that is not going to be mandatory for the user to lookup.

I am not sure how we plan on handling this case,and if that's something specific and not related to this topic of discussion.

**Comment by SaschaAdler** [comment]
All of the slugs we have that don't have prefixes are ones we've created from what are currently "collection tags" for unordered, thematic Collections. These are things that haven't been imported from the preservation platform and don't have depositor prefixes. It's pretty unlikely that a staff member will want to add a large list of these to a collection, especially since there isn't a large list of them to add in the first place, and so I wouldn't worry about them affecting looking up slugs in batch.

We won't want to add prefixes to single-slug lookups, either.

**Comment by RussellMcOrmond** [comment]
I think this is another example where it would be good for us to get something visible for staff to look at, and then ask specific questions about preferences when we have something for them to look at.

It might be that the tool that launches Smelter (currently called Archival Manifest) will be the only thing they will want to use prefixes with in the future.  Maybe all the slugs will be in their databases in full.

Then again, I suspect the metadata uploader will need it, unless the team puts the full ID in a different field as it is only part of the ID that is currently in 590.

**Comment by SaschaAdler** [comment]
Accessor's `.slug.resolveMany` has an optional `prefix` parameter, which is as far as Accessor will go with this, I think.

We'll see what the interface ends up as but I don't think there needs to be more thinking about it here.
