### ISSUE TITLE
Decide container and access policy for OCR files.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#63]
Currently OCR data exists in two places:

* PDF files still exist in the preservation platform, and we refer to them there.
* XML files exist in the access platform, part of /v1/AUTH_crkn/access_metadata/$canvas

We documented our intentions in https://github.com/crkn-rcdr/Access-Platform/blob/master/Policy/Access-Object-Storage-scheme.md to copy images and PDF files to a new access_files container.

I am wondering if we have any reason to consider anything different, focusing on policies.

* Do we want to store files in a container that is publicly readable, and doesn't need a TempURL key for downloads?
* Do we want the metadata files to be downloadable as well, also possibly without TempURL key?

**Comment by SaschaAdler** [comment]
I'm in favour of avoiding the TempURL requirement for things that we intend anyone to be able to download. I imagine we're more worried about heavy scraping traffic than giving people unrestricted access to a Swift container that only contains things we mean them to have unrestricted access to, and scrapers can just go ahead and generate TempURLs from CAP or wherever they'd be available, which would then slow us down even more.

Does Swift have policies about restricting the listing of content in a container which has no restrictions on downloading content? Depending on the workflows we set up, there might be things on there that aren't linked to publicly that we don't (yet) want people to see.

**Comment by RussellMcOrmond** [comment]
https://docs.openstack.org/swift/latest/overview_acl.html#container-acls

Read access to files is separate from list objects, so we can set a container to allow read, no write, no list objects for unauthenticated access.


The design we have to do now is to separate our different object types to be stored in appropriate containers, as policies are per-container and not per-directory or per "file".

**Comment by SaschaAdler** [comment]
One distinction we'll probably want to make is between files that we don't process for public consumption, and files that we do. For example, i expect that we won't want our access image store to be publicly available, since we use a IIIF image server to handle that.

I wonder whether this distinction also makes sense for OCR PDFs and XML files. We might want to build a small PDF service for stitching PDFs together, for example, and as such downloading the single-page PDFs directly from Swift makes less sense. Similarly, annotation servers might be the only way we want to share OCR XML publicly (at least regularly).

Alternatively, we could make files available both in their raw state and processed by whatever servers we need to run? I'm not sure.

**Comment by RussellMcOrmond** [comment]
* We don't want to have images available publicly, as we have a `canvas` document we want to load and confirm that access is allowed (it wasn't taken down/etc).

Because of this, I'm wondering if we should be thinking about restricting the PDF and XML files in a similar way, ensuring that the flags in the `canvas` document are honoured.

We use TempURL for PDF downloads currently, and previously had a proxy.  If we wanted to have IIIF presentation documents not have a time limited URL in them then we will probably want to go the proxy route. If we don't care, then TempURL is fine.

Unless we want to move PDF files out of an "anonymous read allowed" container when there is a restriction, we may be stuck not using that type of policy.  Alternatively when a restriction is made we can assume we re-generate the multi-page PDF with "this page removed" pages in the PDF just as we would serve from Cantaloupe.
