### ISSUE TITLE
Create collection records for Heritage and Parliament "subcollections"

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#64]
Heritage subcollections are identified using the `identifier` field. We can create actual collection objects for them. It might be worth using this to figure out a post-loadseries workflow for moving members from a parent collection to a child collection.

**Comment by RussellMcOrmond** [comment]
We have been using `loadseries` for longer than I thought we might be.  If it makes sense to consider how we want to do this early, and incorporate it into `loadseries`, then we can do that.

What would the algorithm be for determining the membership of each branch of a "parl" tree?

**Comment by RussellMcOrmond** [comment]
This ties directly into what we want Accessor to return for "what collections am I a member of".  Is this a set of breadcrumb paths given a manifest can be in multiple branches?

I believe the idea is to be able to have navigation that allow people to go "up" any of the various branches a given manifest or collection is part of.

Do you have a visualisation in your head what this looks like, and be able to draw something out (image likely easier than the ASCII art you did in https://github.com/crkn-rcdr/CIHM-Meta/issues/33 )?

**Comment by SaschaAdler** [comment]
It's a set of paths, yes. And the question you're asking isn't so much "what collections am I a member of" but "what collections are my ancestors" (wording pending), which in the new model are two different things, and accessor will need to provide answers for both. Essentially both ask the same question, but one with a recursive depth of 1, and the other with a theoretically infinite recursive depth. I imagine there will be some contexts where we don't want to spend the cost to perform the latter question.

What does this look like in an admin tool, or for the public? I don't know. Breadcrumbs seem like the most obvious metaphor, at least for the public, and in that case we can restrict what paths show up based on the root collection of the portal they're looking at.
