### ISSUE TITLE
Orchestrate the use of a Kivik instance throughout the repo for development

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#66]
The current instructions involve some manual steps.  There is a REST API we can talk to in order to automate the setup if we wished.

Is there interest, or is the documentation of a few manual steps for developers sufficient for now?

https://docs.couchdb.org/en/latest/api/server/configuration.html

**Comment by SaschaAdler** [comment]
I'm exclusively using Kivik for this. Do we need the separate docker-compose config at this point?

Ideally Kivik instances are suitable for whatever local development is required, although one thing they don't support (pretty intentionally) is persisting data on the host.

**Comment by RussellMcOrmond** [comment]
I think this is up to the primary developers, which isn't me :-) 

I'm fine with using Kivik for launching, when a local database is what I need. Kivik allows launching CouchDB on a fixed port, making config changes to point to the local database easy..

**Comment by SaschaAdler** [comment]
I have plans for this, some of which is going to involve a little kivik/nano work.

See https://github.com/crkn-rcdr/kivik/issues/68, https://github.com/crkn-rcdr/nano/issues/2

What I'd like to be possible, and the default situation, is that a Kivik instance pointing to /couchdb is enough for testing everything else in this repo. The issues above will allow for that to be the case without every module in this repo depending on Kivik when they just want to point to the dev couch server.

**Comment by SaschaAdler** [comment]
#140 helps with this but there's still work to be done.
