### ISSUE TITLE
Questions about new "access" schema

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#67]
* Should `slug` be mandatory?  I have temporarily put in `$entry->{slug}=".";`  to pass tests.
* Should `viewingDirection` be mandatory if it has a default?
* I assume "contiuous" for `behaviour` was intended to be "continuous". Should it be mandatory if it has a default?

**Comment by SaschaAdler** [comment]
Slug shouldn't be mandatory. I've noticed the issue in the work I'm doing as well.

From what I can tell, `default` in a JSON Schema is used more as a guide to people working on the schema, and not something that validators necessarily check, since validators don't also add the default values to objects as they're validating them, necessarily. I suppose these fields don't have to be mandatory, either.

**Comment by SaschaAdler** [comment]
I think `behavior` (and apologies for the American spelling, but that's how it is in the IIIF spec) should be mandatory on collections, since it's how we're handling whether or not the collection order has meaning. Manifests, not so much.

**Comment by RussellMcOrmond** [comment]
I am currently running the `mergeaccess` tool in a test mode where it validates the output it would otherwise put into the database.
https://github.com/crkn-rcdr/CIHM-Meta/pull/36

I am hoping that we can finalise the schema and how we want to transform existing documents early next week, so we can complete this database merge by the end of the week.

**Comment by RussellMcOrmond** [comment]
One additional question.

Is an Alias intended to have a NOID as an ID, or just a database generated unique ID?

For `mergeaccess` the intention was to use https://docs.couchdb.org/en/3.1.1/api/database/bulk-api.html#db-bulk-docs . For validation I need to allocate and fill in the ID for aliases earlier, but want to ensure it is fine that I use CouchDB's "/_uuids" interface rather than allocating a generic noid.

At the moment there seems to only be two aliases, so it doesn't matter that much, but this may change..

**Comment by SaschaAdler** [comment]
I think ideally everything in the `access` database has a Noid for an id, if only for consistency. It also makes building the schemas less complicated.

I think the aliases we have currently set up are bogus ones we put together just to test out that we can alias slugs (`1813` and `1814`, right?) so we can trash them for now if we don't want to answer this question right now.

**Comment by RussellMcOrmond** [comment]
Maybe throw a test Alias somewhere for us to be testing (fixture, etc), and we can delete the ones from the database for the purposes of this conversion.

Want me to delete?  My error report has the noid.

**Comment by RussellMcOrmond** [comment]
```
{
  "_id": "69429/s0dv1cj88k2m",
  "aliasedSlugs": [
    "1813",
    "1814"
  ]
}
```

**Comment by SaschaAdler** [comment]
I was thinking something like this: https://github.com/crkn-rcdr/Access-Platform/blob/e7111c9baaa82b4ab7f3126f7934f28f07dc0dc7/data/src/access/common.spec.ts#L7-L12

**Comment by SaschaAdler** [comment]
@RussellMcOrmond Mind if we close this? It might be better to ask individual questions in their own issues. (Or we could use Discussions for that?)

**Comment by RussellMcOrmond** [comment]
I believe we have handled each of these questions.
