### ISSUE TITLE
Add representatives of remaining access object `type`s to fixtures.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#69]
Noticed an issue by accident while validating documents in our legacy `manifest` database.

* https://numeris-demo.canadiana.ca/view/numeris.TV_1993_FA00_074/  - Has an "About" with a URL and nothing else.
* https://numeris.canadiana.ca/view/numeris.TV_1993_FA00_074/ -- says "There is no content yet for this title. Please check again later."

The same problem doesn't exist with other Born Digital manifests, for example:

* https://numeris-demo.canadiana.ca/view/numeris.TV_2006_FA00_002/1?r=0&s=1
* https://numeris.canadiana.ca/view/numeris.TV_2006_FA00_002/1?r=0&s=1

As part of our work to merge databases and schemas #67, we will want to force tests for the born digital to ensure everything continues to work correctly.

**Comment by SaschaAdler** [comment]
Just looked into this and the broken first object appears to have entered `copresentation` as a series instead of a `document`. Not sure what happened there.

Once we ensure a PDF manifest is added to our fixtures, I think we can close this issue.

**Comment by SaschaAdler** [comment]
Not related to PdfManifests specifically, but we will also want an Alias fixture, even if it's handcrafted for now.

**Comment by RussellMcOrmond** [comment]
The problem is http://iris.tor.c7a.ca:5984/_utils/index.html#database/internalmeta/numeris.TV_1993_FA00_074

This record claims this is sub-type "series", which means it shows up in internalmeta/_design/tdr/_view/doctype  as a "series".


The METS record in the repository looks fine, so not sure what happened -- but the wrong thing that happened seems to have happened in the legacy platform.

I've updated the sub-type to "document" and updated the "updated" field, and will see what happens with press/etc.


```

<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" OBJID="TV_1993_FA00_074">
  <mets:dmdSec ID="dmd.TV_1993_FA00_074">
    <mets:mdWrap MIMETYPE="text/xml" MDTYPE="DC">
      <mets:xmlData>
        <simpledc xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:identifier>TV_-1993-00086</dc:identifier>
  <dc:title>Kingston - Television Market Report/Rapport de marché - Fall/Automne 1993</dc:title>
  <dc:date>1993</dc:date>
  <dc:language>eng</dc:language>
  <dc:language>fra</dc:language>
  <dc:subject>television TV télévision -- market report/rapport de marché -- Fall 1993/Automne 1993 -- Kingston</dc:subject>
  <dc:description>Fall/Automne 1993: Oct/oct. 28 - Nov/nov. 3, Nov/nov. 4-10, Nov/nov. 11-17</dc:description>
</simpledc>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:fileSec>
    <mets:fileGrp USE="master"/>
    <mets:fileGrp USE="distribution">
      <mets:file ID="distribution.TV_1993_FA00_074" MIMETYPE="application/pdf">
        <mets:FLocat LOCTYPE="URN" xlink:href="document.pdf"/>
      </mets:file>
    </mets:fileGrp>
    <mets:fileGrp USE="canonical">
      <mets:file ID="canonical.TV_1993_FA00_074" MIMETYPE="text/html">
        <mets:FLocat LOCTYPE="URL" xlink:href="http://numeris.canadiana.ca/view.TV_1993_FA00_074"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap TYPE="physical">
    <mets:div TYPE="document" LABEL="Kingston - Television Market Report/Rapport de marché - Fall/Automne 1993" DMDID="dmd.TV_1993_FA00_074">
      <mets:fptr FILEID="distribution.TV_1993_FA00_074"/>
      <mets:fptr FILEID="canonical.TV_1993_FA00_074"/>
    </mets:div>
  </mets:structMap>
</mets:mets>
```

**Comment by RussellMcOrmond** [comment]
I re-ran Hammer, and it created a different type of "Broken" page for https://numeris.canadiana.ca/view/numeris.TV_1993_FA00_074/ , but now clearly a document and not a series.


I realise what happened now, and how long ago the problem was caused.

For the "working" born digital there is a series of page-leven div's which fake "OCR" by extracting text out of the born digital PDF's.  In this case a smaller METS record pointing at the PDF exists.

Post-split we will be able to ensure that Smelter ignores AIPs that have no files in them, and creates appropriate manifests regardless of what metadata type is in the METS record.  This way any access-platform level features within preservation data can be ignored.


A born digital PDF will be a born-digital PDF, and page-level search won't be based on fake txtmap entries.  We will want to decide what to do with the `pageLabels[]` field when a METS record offers no page labels.  `pageLables[]` is current marked as required in the schema.
