### ISSUE TITLE
Master application HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#7]
I want to put this in the back of people's minds  (@SaschaAdler , @wfms ) as we move forward.

I had hoped to spend some time with container orchestration, and see how it could help, but we haven't gotten that far yet.

The idea is that each of our (soon to be 4, 2 in each of UofT and UofA) Application Servers would have something listening on port 80 and port 443.  Virtual hosts and SNI would then be used to proxy from these machines to the appropriate internal container(s) that handle that service.

On top of this we would use round robin DNS and virtual IPs like we currently use for Swift, such that bringing a node down doesn't disrupt connections to these proxies.

I'm not thinking Apache, but something along the idea of HAProxy or nginx.  What I don't know about is service discovery (where is the container offering a given service, and which one to connect to if more than one instance is being run), which is something which orchestration software such as Kubernetes are intended to help with.

**Comment by RussellMcOrmond** [comment]
The production deployment is being completed https://github.com/crkn-rcdr/Systems-Administration/issues/80

The next stage will be for developers to have a sample haproxy configuration file when doing local testing of applications.   Instead of applications handling SSL internally, applications will need to read a series of header files that the proxy adds.

* X-Forwarded-For - The IP address of the client.
* X-Forwarded-Host - the host the request is for (CAP uses this to distinguish portals)
* X-Forwarded-Proto - "http" or "https"

Details and examples can be seen via:  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto 

Some other tickets created for application updates to support these headers.

* https://github.com/crkn-rcdr/amsa/issues/5
* https://github.com/crkn-rcdr/upholstery/issues/6
* https://github.com/crkn-rcdr/sapindale/issues/25

I believe @SaschaAdler has decided to put the sample configuration that developers will use in this repository, along with a script to generate a self-signed wildcard certificate and related documentation.

**Comment by RussellMcOrmond** [comment]
I'll check off items from the lists on https://trello.com/c/cbdXxZAN/104-haproxy as they are completed.

**Comment by SaschaAdler** [comment]
We've done this work (and it's really great).
