### ISSUE TITLE
couchdb testing strategies

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#74]
I can think of a few ways to go about testing our CouchDB configuration.

1. The method that already works with Kivik. We store fixtures in JSON files, deploy them to a local Kivik instance, check that our views work, run updates on the fixtures and see what happens, etc. If we need to test everything and we don't want to mangle the fixtures too much, the number of files grows a lot. Also, do we commit them to the repo, or not?
2. We use replication to generate our test fixtures. For each database, Kivik can read an array of identifiers that gets used as the `doc_ids` parameter in a call to [`/replicate`](https://docs.couchdb.org/en/stable/api/server/common.html#replicate).

There are also questions of how we want to run the tests themselves, and if we can parallelize things.

**Comment by RussellMcOrmond** [comment]
I was hoping we would do a bit of both when authoring/testing design documents.  The quick test of a design document is against fixtures, but if we want a larger data set we would bring in more data from a replication.

Is this ticket to discuss the more complex application testing, for instance for what will be needed for `accessor`?

**Comment by SaschaAdler** [comment]
I could see us using either file fixtures or replication to bring in test data for either design doc testing or testing Accessor-like functionality (which is largely going to be using design docs, anyway). We could do both, and it might make sense to, although keeping the fixtures current and relevant will be important.

I plan on doing some work with Kivik to ensure that tests can run in a manner that doesn't, say, pull fixtures for every test file, or something silly like that.

**Comment by SaschaAdler** [comment]
Hey, Kivik tests work pretty well with fixtures as they are. I don't think we need to worry about larger integration tests right now, as what we can do with this will already make a huge difference.

I'll close this for now, since I don't know when we'll get to anything more orchestrated.
