### ISSUE TITLE
Lapin+Accessor functionality for metadata bus.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#81]
This ticket will be used to document functionality used by the metadata bus which can hopefully be migrated to Lapin+Accessor

Currently using:

https://github.com/crkn-rcdr/CIHM-Meta/blob/main/lib/CIHM/Meta/REST/access.pm
https://github.com/crkn-rcdr/CIHM-Meta/blob/main/lib/CIHM/Meta/REST/canvas.pm

* bin/walk-canvas-orphan
  *  Needs function to look up if a given canvasnoid is used by any manifest (currently via /access/_design/noid/_view/canvasnoids) to find any canvas that isn't being used.
  * Currently using a paging through canvases to get all canvas documents to then check if that canvas is used.
  * Updating canvas documents to set `orphan` field based on whether any manifests are were found using the canvas.  Currently doing as bulk update of many at a time (Otherwise would be far too slow given number of canvases).
* Hammer2
  * Function to access the /_design/metadatabus/_view/hammerQueue  - current access uses a limit and an optional skip.
  * Ability to post results by noid  (Using /_design/metadatabus/_update/hammerResult/ )
  * Ability to get full document by noid (Hammer needs to access full `access` documents)
  * Ability to get slim document by noid (using _find, likely by passing in array of fields to return. I currently need `["slug","behavior"]` )
  * Get collections a noid is in (Using /_design/access/_view/members )
    * Note: This will need updating to handle collection trees, so if Accessor is soon it may be best to do it there and not bother with Perl version of logic.
  * get an array canvas documents based on an array of canvas ID's. 
* Smelter
  * A method to create new manifest documents.  Currently I create an entire document and post it to "/_bulk_docs", but I do a validate first.  I'm assuming the plan is to have a way to validate/create as one operation.
  * Post an array of newly created canvases.  I currently use /_bulk_docs to post after validating.
  * **Get a noid from slug is already done** (Used to check yet again that the slug isn't a duplicate -- best to be safe to avoid that oddness).
  
* bin/makepublic
  *  Pre-split tool... going away after  
  *  Needs functions to `publish` and `unpublish` based on slug (update function based on noid).  Functions should only change the document if the publish/unpublish status is changed (IE: a flag that means do nothing if the status doesn't change). Ideal if this can accept multiple updates as one request, rather than a request per noid.
* loadseries
  *  Pre-split tool... going away after  
  * Leaving this as question.  I could port this to using Lapin+Accessor partly to test out functionality, but not needed past the split being completed.

**Comment by RussellMcOrmond** [comment]
I'd like to discuss API for collection management with @SaschaAdler 

What `loadseries` does is a bit unusual, but might be informative.   Essentially for a given collection noid there is a desire to `add` an array of other nodes, `subtract` an array of other noides, or make the members `equal` to an array of other noids.

This isn't only managing the `members` array, but also ensuring that the changes (additions or subtractions) initiate updateInternalmeta for the members.  This will need to note which members changed and only manipulate them, and not all members of a collection (most of which won't have changed).  `loadseries` hasn't been manipulating the members of collections, but it was also intended to be a one-off tool and not regularly run as we have been doing.

My hope is we can move this functionality into Lapin+Accessor, and I can then be using the correct algorithm with `loadseries`.

**Comment by SaschaAdler** [comment]
I've split your comment above into its own issue. We can ruminate on further requirements in accessor for back-end tools, and I'll also want to get lapin available to you in Docker at some point, although I think developing in this repo in general may require running Node on your machine directly.

**Comment by RussellMcOrmond** [comment]
Apologies, but I believe https://github.com/crkn-rcdr/CIHM-Meta/issues/40 is a branch of this discussion.  Let me know if we should close that and we can continue the discussion here.
