### ISSUE TITLE
Staff update tracking

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#83]
Currently, when an access object is edited by staff (which doesn't actually happen yet, but bear with me), `updateInternalmeta.requestDate` is updated to cause the metadata bus queue to process the object. It would be nice to keep track of which staff member performed this edit, so that any problems with the metadata bus processing can be directed to that person specifically. In the future we will also want to create these queues for multiple processes per object, or for back-end processes on other data (e.g. `dmdtask`).

At first I thought that adding staff information to a generic `updated` field was the best approach for this, but now I'm wondering if we just want to add staff information along with `requestDate` in the [`ProcessUpdate`](https://github.com/crkn-rcdr/Access-Platform/blob/main/data/src/util/ProcessUpdate.ts) specification. Although, again, per #72, we need to keep track of staff updates generically, and not all updates will request changes in these queues. We could always track both:

```json
{
  "updated": {
    "date": 1234567.89,
    "by": {
      "name": "Sascha Adler",
      "email": "sadler@crkn.ca"
    }
  },
  "updateInternalmeta": {
    "requestDate": 1234567.89
  }
}
```

but I wonder if we'd rather attach the staff member to the generic update or the queue request (or both??).

@RussellMcOrmond curious for your input here.

**Comment by RussellMcOrmond** [comment]
`updateInternalmeta` is itself ephemeral in that it will be used only as long as we have an `internalmeta`.

It almost feels like there should be a separate field for when we know a `by`, as I don't see value in storing the "name" of a service that makes an update.

At this point my recommendation would be a third field that looks likw what you suggested above (date and by), but that is separate from `updated`.

I recommend we don't think of this as tracking, but a reminder.  I don't think keeping an audit trail or anything similar would be worth the work.

**Comment by SaschaAdler** [comment]
`updateInternalmeta` has a shelf life but I'm hoping the ProcessUpdate specification that it uses can last longer, which is why I bring it up.

Do processes like Hammer and whatever other daemons we put together need to update `updated`, if they also update the ProcessUpdate they're tied to, and especially if they don't change anything in the object itself? Do we want an `updated` field that only keeps track of human intervention?

We could certainly specify that `by` is optional, or we could come up with some scheme to say "Smelter created this", or we could even keep track of who imported something in Smelter and save that to the new objects Smelter has created.

**Comment by RussellMcOrmond** [comment]
I've added @brittnylapierre and @DivyaKrishnan26 to this issue.

I think when it comes to displaying who the last staff member was that worked on a record, that this is more of a UI question that relates to the user experience.  From a systems/etc point of view, I'm just so happy we are moving away from "stick a file in a special directory" for this type of work :-) 

If requested, I can have Smelter pull staff information from a `dipstaging` document and ensure that is appropriately stored in a `manifest`.  Having a manifest say that "Smelter" created it doesn't sound very interesting from a user perspective.

The metadata bus has its own logs if systems staff need to track problems, so we don't need to be thinking of these fields for that purpose.

**Comment by RussellMcOrmond** [comment]
I believe in our meeting yesterday that @brittnylapierre is assigned this now?

**Comment by SaschaAdler** [comment]
So, I've already come up with a spec in the initial comment, which has this TypeScript type:

```ts
type StaffUpdate = {
  by: {
    name: string;
    email: string;
  };
  date: Timestamp
}
```

The `by` property might be unnecessary, though. We could specify this instead as

```ts
type StaffUpdate = {
  name: string;
  email: string;
  date: Timestamp;
}
```

On the other hand, it might be nice to have a Staff (or User, or whatever) type, like:

```ts
type User = {
  name: string;
  email: string;
}
```

which we can use elsewhere (like the admin tools session) and it can be extended later if we'd like. If we do this, we can use the first definition, rewritten as

```ts
{
  by: User;
  date: Timestamp;
}
```

I don't know if it really matters, and I can't decide between these choices right now, so go with your gut.

**Comment by jjfriedman** [comment]
If you care what a non-technical guy thinks (and if I'm even allowed to be here), I think having a separate Staff/User type makes sense with the possibility of later extension.

**Comment by brittnylapierre** [comment]
I agree with Jason too I like the User option as well

**Comment by RussellMcOrmond** [comment]
I agree with Jason, and am happy to find that a non-developer is periodically noticing these discussions as well.

For the `smelt` field in `dipstaging`, the user is both the user who initiated the smelt as well as the user that would be listed for the manifests a smelt creates.

**Comment by SaschaAdler** [comment]
Separate User type it is! We can also use it in the admin tools session, and I'm sure it will turn up elsewhere.

@RussellMcOrmond I'm not planning on adding User to ProcessUpdate, so it's not going to show up inside the `smelt` property, but in a new `staff` (or `user`? we should really pick one everywhere and stick to it) property.
