### ISSUE TITLE
Production Docker image for the admin tools

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#86]
Keeping track of workspace dependencies locally means that Docker images can't be built just by copying some files in a particular service's directory. A more comprehensive solution is required.

**Comment by RussellMcOrmond** [comment]
Some thoughts I had last night.

Thus far we have regularly been creating separate Docker images for different applications/services/etc.  I am wondering if instead we want to build a single image, and launch different containers with different parameters to a script used as the ENTRYPOINT.

https://github.com/crkn-rcdr/cihm-metadatabus is an example I built from someone else's suggestion.

docker-entrypoint.sh is used to separate "solrstream" (a small perl script that could have been separated, but was kept in same image to simplify), "fullbus" for the metadata bus, and just running the command as the TDR user.

This image launches CRON and Postfix, but something else entirely can be done with the Access-Platform Docker image.  I can create a separate Image for email sending that is run along with access-platform, and possibly use https://www.npmjs.com/package/node-schedule  for scheduling modernised metadata-bus activities.


With modern Docker there is an `--init` flag , so building `tini` inside the image is no longer required.  This wasn't upgraded with cihm-metadatabus as I believe the longer-term intention is to get rid of that container and have a majority of code within this repository.

**Comment by SaschaAdler** [comment]
I'm going to limit the scope of this issue to `admin`. Running Couch locally works (with a few caveats) and we can sort out `lapin` at a later time.
