### ISSUE TITLE
Clean up manifests with missing canvases.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#89]
Smelter periodically generates these errors:

```
Could not write to socket: 'Connection reset by peer'

Caught: dbupdate of 'canvas' return code: 599
```

In this case the manifest document was written, but not all the canvas documents were.

It is also possible we need a tool to walk manifests to confirm that their canvases are intact, allowing staff to remove and retry creating broken manifests.

**Comment by SaschaAdler** [comment]
Do you know if the canvases are broken because of a bug in Smelter, or a bug in the AIP being imported?

**Comment by RussellMcOrmond** [comment]
None of the above.:-)

Networks and services are not 100% reliable, and there is a need to handle cases when services are temporarily unavailable.  In this case some canvases were written, but not all.  Trying to immediately do an "undo" also wouldn't work, as we don't know if the "undo" would fail for the same network/service outage reason.

Part of the need to author various `walk` tools looking for odd links between data is to detect this type of problem in our data, and provide feedback to staff to fix up.

**Comment by SaschaAdler** [comment]
Silly question: Smelter writes the manifest document before it writes the canvas documents?
Sillier question: Smelter writes canvas documents sequentially instead of as one big bulk insert?

I agree that we need to write resilient code, but how much of that resilience can take place when the write is supposed to happen, so that we don't have to piece together what went wrong after the fact?

**Comment by RussellMcOrmond** [comment]
All good questions.

CouchDB is only one of the services we are communicating with.  Even if the CouchDB writes are done in the best way (I didn't look to check), we still need to walk the Swift containers to compare noids to detect when some were written when others were not.  A walk will still need to exist to confirm that the files which CouchDB says were stored were actually stored.

Given the different things that could go wrong while Smelting, we will still need to walk to detect issues that we aren't able to handle earlier.  This is all similar to what we are doing in preservation with validation, ensuring the files the CouchDB database says we have we still have.

**Comment by RussellMcOrmond** [comment]
This relates to #333 .

Smelter can be enhanced to only write a manifest when all canvases have been stored, but part of making this more robust is to be able to "resume" when there are failures (IE: be able to notice some canvases were created, even if all weren't).

**Comment by RussellMcOrmond** [comment]
Moving this into "Access Files/Data Migration", as this is part of the current work to clean up canvases.

**Comment by RussellMcOrmond** [comment]
The updated Smelter will only write the manifest once all the canvases have been confirmed.  This will avoid new manifests with missing canvases, but I still need to walk to find any past problems.

I will take a closer look at Hammer2, but I suspect that it is already accomplishing this walk for us.  I will check what it does in the case when a canvas is missing or otherwise malformed.

**Comment by RussellMcOrmond** [comment]
Hammer2 will output an alert if any canvases are missing.

https://github.com/crkn-rcdr/CIHM-Meta/blob/d32e0454bd50fa3ed7fff5b20e0d9d57aac3d947/lib/CIHM/Meta/REST/canvas.pm#L74-L96

https://admin.canadiana.ca/couchview/access/metadatabus/hammerUnprocessed  -- indicates every document in `access` has been processed.

https://admin.canadiana.ca/couchview/access/metadatabus/hammerStatus -- shows all the messages, and none of them relate to missing canvas documents.
