### ISSUE TITLE
Design schemas and plan for tools to generate Manifest-level multi-page PDFs

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#90]
https://github.com/crkn-rcdr/Access-Platform/blob/master/Databases/schemas/manifest.json has an "updatePdf" field that can be used to create a view for a queue.

* For every manifest where this field is blank, or where the updatePdf.requestDate>updatePdf.processDate
* Check if there is an ocrPdf file in the manifest, but no ocrPdf in the canvases.
  * split the multi-page ocrPdf to generate separate single-page ocrPdf files, and return.
* Check if there is an ocrPdf in all the canvases, and the count or size is not higher than a maximum (Policy needed)
  * join the single-page canvas ocrPdf files into a multi-page ocrPdf, and store associated with manifest.

**Comment by SaschaAdler** [comment]
It was only deprecated because the schema only contains the stuff required to get the split done. :)

**Comment by RussellMcOrmond** [comment]
Note that #153  completed the first part of the work: "split the multi-page ocrPdf to generate separate single-page ocrPdf files."

The remaining work is to: "join the single-page canvas ocrPdf files into a multi-page ocrPdf, and store associated with manifest."

**Comment by brittnylapierre** [comment]
Generating PDFs: 

- [x] always when OCR is made, 
- [ ] always when something is published, 
- [ ] and always when the canvases change order.
