### ISSUE TITLE
Displaying and editing an access object's membership / ancestry

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#95]
When editing a manifest or collection, it will be useful to display the collection's it's a member of; ideally we'd also show the full ancestry, so that no one will want to add the object to a collection it's already "in".

We'll also want to provide a button that revokes an object's membership in a particular collection. (Heck, we could add a little interface to look up a collection slug so that the object can be made a member of it.)

**Comment by SaschaAdler** [comment]
There's a component that does some of this at https://github.com/crkn-rcdr/sapindale/blob/main/src/components/Collection/ParentsList.svelte. This relies on a `parents` list which might be built differently in #94.

**Comment by SaschaAdler** [comment]
This depends on	#94.

**Comment by SaschaAdler** [comment]
Hit `close` by accident.

**Comment by SaschaAdler** [comment]
I'm not entirely sure what this should look like; we want to display the collections that this object is a member of, but also potentially demonstrate its full descent.

**Comment by RussellMcOrmond** [comment]
I note this also says "editing".  I know you said before that you don't want one of those tree browsers like the Microsoft Regedit, but it might be that type of thing will be the best option.

I'm of course going to suggest using what other people have written -- I did a quick search and found https://www.npmjs.com/package/tree-editable

**Comment by SaschaAdler** [comment]
The only edit that I can foresee making from this view is removing a leaf from the collection tree. I don't think using a tree view makes as much sense for that as just a list of breadcrumbs.

**Comment by DivyaKrishnan26** [comment]
@SaschaAdler  should this be assigned to you?
