### ISSUE TITLE
`dipstaging` schema and couch design

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#99]
The `dipstaging` database has a record of preservation packages that are available for import into the access platform. Its schema and couch config should be integrated into this codebase.

The StaffUpdate work in #83 might be relevant.

**Comment by SaschaAdler** [comment]
The `dipstaging` schema can be found here: https://github.com/crkn-rcdr/Access-Platform/blob/main/deprecated/Databases/dipstaging/schema.json

I think this is what its corresponding type, which would be defined in `src/dipstaging/index.ts`, should look like:

```ts
{
  id: string; // maybe use Slug here too?
  slug?: Slug;
  repos: string[];
  reposManifestDate: Timestamp;
  reposDate: Timestamp;
  METS: {
    path: string;
    md5: string; // we may want to create an md5 utility class, as we use it in multiple places
  }[];
  METSManifestDate: Timestamp;
  METSDate: Timestamp;
  updated: Timestamp;
  smelt?: ProcessUpdate;
  staff?: StaffUpdate; // or "User" as specified in my comment in #83; this property could also be called "user" if we want; this is a new field
}
```

We'd also define a DipstagingDocument type in `src/couch/dipstaging.ts`, similarly to how AccessDocument and CanvasDocument are defined.

**Comment by RussellMcOrmond** [comment]
`id: string; // maybe use Slug here too?`



The slug and the ID of the AIP can regularly be different. The slug is a field which the user types in, and is data for a Smelt. We could move that field to be within `smelt` if we wanted, so make it more clear that it is data for a smelt and not data that is used in any other way.



The ID is something which RepoSync sets when it creates documents based on the existence of AIPs in the repository.

https://github.com/crkn-rcdr/CIHM-Meta/blob/main/bin/reposync
https://github.com/crkn-rcdr/CIHM-Meta/blob/main/lib/CIHM/Meta/RepoSync.pm




At the moment, `dipstaging` has a field for all the data that could be sent into CIHM::Meta::REST::dipstaging::update_basic_full()

https://github.com/crkn-rcdr/CIHM-Meta/blob/main/lib/CIHM/Meta/REST/dipstaging.pm#L78


It is quite possible that this will get replaced by a REST call to lapin at some point, in which case fields which the front-end developers don't see a value to showing staff can be deprecated.

As an example, `dipstaging` has `METS`, `METSManifestDate` and `METSDate` which aren't used.


* `reposManifestDate` is used by a view and is displayed. 
* `repos` array is also displayed.
* `smelt` is the core field, and is displayed and manipulated via the "doAction" in svelte, to call /dipstaging/updates.json . I expect with Accessor that this back-end stuff will get done differently.  It's a function based on a document _id and passing in a slug.

**Comment by brittnylapierre** [comment]
Awesome thanks @SaschaAdler  and @RussellMcOrmond 

I actually started working on it without noticing this so this helps me place the files I made better, I wasn't sure where made the most sense to put them! 

So far I wasn't too far off your src/dipstaging/index.ts definition too Sascha! I didn't notice the timestamp type, and I ended up making a util (type/schema?) for the Mets array too. How do you know when to make a (type/schema definition - not sure what to call it) and when to just define inline-style? I'll change what I have to match yours.

I'm sure you'll probably have more things you want me to edit once I make a pull request tho but thanks again for the extra info!

Oh - should I comment out or delete the unused properties (METS, METSManifestDate and METSDate?)
